// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ChatSessionCreateData, ChatSessionCreateErrors, ChatSessionCreateResponses, ChatSessionDeleteData, ChatSessionDeleteErrors, ChatSessionDeleteResponses, ChatSessionGetManyData, ChatSessionGetManyErrors, ChatSessionGetManyResponses, ChatSessionGetOneData, ChatSessionGetOneErrors, ChatSessionGetOneResponses, ChatSessionUpdateData, ChatSessionUpdateErrors, ChatSessionUpdateResponses, FolderCreateData, FolderCreateErrors, FolderCreateResponses, FolderDeleteData, FolderDeleteErrors, FolderDeleteResponses, FolderGetManyData, FolderGetManyErrors, FolderGetManyResponses, FolderGetOneData, FolderGetOneErrors, FolderGetOneResponses, GetFileData, GetFileErrors, GetFileResponses } from './types.gen';
import { zChatSessionCreateBody, zChatSessionCreateResponse, zChatSessionDeletePath, zChatSessionDeleteResponse, zChatSessionGetManyResponse, zChatSessionGetOnePath, zChatSessionGetOneResponse, zChatSessionUpdateBody, zChatSessionUpdatePath, zChatSessionUpdateResponse, zFolderCreateBody, zFolderCreateResponse, zFolderDeletePath, zFolderDeleteResponse, zFolderGetManyResponse, zFolderGetOnePath, zFolderGetOneResponse, zGetFilePath, zGetFileResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ApiClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ApiClient extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<ApiClient> = new HeyApiRegistry<ApiClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ApiClient.__registry.set(this, args?.key);
    }
    
    /**
     * Get File
     */
    public getFile<ThrowOnError extends boolean = false>(options: Options<GetFileData, ThrowOnError>): RequestResult<GetFileResponses, GetFileErrors, ThrowOnError> {
        return (options.client ?? this.client).get<GetFileResponses, GetFileErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zGetFilePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zGetFileResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/files/{filename}',
            ...options
        });
    }
    
    /**
     * List Sessions
     */
    public chatSessionGetMany<ThrowOnError extends boolean = false>(options?: Options<ChatSessionGetManyData, ThrowOnError>): RequestResult<ChatSessionGetManyResponses, ChatSessionGetManyErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<ChatSessionGetManyResponses, ChatSessionGetManyErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zChatSessionGetManyResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/chat/',
            ...options
        });
    }
    
    /**
     * New Session
     */
    public chatSessionCreate<ThrowOnError extends boolean = false>(options: Options<ChatSessionCreateData, ThrowOnError>): RequestResult<ChatSessionCreateResponses, ChatSessionCreateErrors, ThrowOnError> {
        return (options.client ?? this.client).post<ChatSessionCreateResponses, ChatSessionCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zChatSessionCreateBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zChatSessionCreateResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/chat/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Session
     */
    public chatSessionGetOne<ThrowOnError extends boolean = false>(options: Options<ChatSessionGetOneData, ThrowOnError>): RequestResult<ChatSessionGetOneResponses, ChatSessionGetOneErrors, ThrowOnError> {
        return (options.client ?? this.client).get<ChatSessionGetOneResponses, ChatSessionGetOneErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zChatSessionGetOnePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zChatSessionGetOneResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/chat/{session_id}',
            ...options
        });
    }
    
    /**
     * Delete Session
     */
    public chatSessionDelete<ThrowOnError extends boolean = false>(options: Options<ChatSessionDeleteData, ThrowOnError>): RequestResult<ChatSessionDeleteResponses, ChatSessionDeleteErrors, ThrowOnError> {
        return (options.client ?? this.client).post<ChatSessionDeleteResponses, ChatSessionDeleteErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zChatSessionDeletePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zChatSessionDeleteResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/chat/{session_id}',
            ...options
        });
    }
    
    /**
     * Update Session
     */
    public chatSessionUpdate<ThrowOnError extends boolean = false>(options: Options<ChatSessionUpdateData, ThrowOnError>): RequestResult<ChatSessionUpdateResponses, ChatSessionUpdateErrors, ThrowOnError> {
        return (options.client ?? this.client).put<ChatSessionUpdateResponses, ChatSessionUpdateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zChatSessionUpdateBody,
                path: zChatSessionUpdatePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zChatSessionUpdateResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/chat/{session_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * List Folders
     */
    public folderGetMany<ThrowOnError extends boolean = false>(options?: Options<FolderGetManyData, ThrowOnError>): RequestResult<FolderGetManyResponses, FolderGetManyErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<FolderGetManyResponses, FolderGetManyErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zFolderGetManyResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/folders/',
            ...options
        });
    }
    
    /**
     * Create Folder
     */
    public folderCreate<ThrowOnError extends boolean = false>(options: Options<FolderCreateData, ThrowOnError>): RequestResult<FolderCreateResponses, FolderCreateErrors, ThrowOnError> {
        return (options.client ?? this.client).post<FolderCreateResponses, FolderCreateErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: zFolderCreateBody,
                path: z.never().optional(),
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zFolderCreateResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/folders/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete Folder
     */
    public folderDelete<ThrowOnError extends boolean = false>(options: Options<FolderDeleteData, ThrowOnError>): RequestResult<FolderDeleteResponses, FolderDeleteErrors, ThrowOnError> {
        return (options.client ?? this.client).delete<FolderDeleteResponses, FolderDeleteErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zFolderDeletePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zFolderDeleteResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/folders/{folder_id}',
            ...options
        });
    }
    
    /**
     * Get Folder
     */
    public folderGetOne<ThrowOnError extends boolean = false>(options: Options<FolderGetOneData, ThrowOnError>): RequestResult<FolderGetOneResponses, FolderGetOneErrors, ThrowOnError> {
        return (options.client ?? this.client).get<FolderGetOneResponses, FolderGetOneErrors, ThrowOnError>({
            requestValidator: async (data) => await z.object({
                body: z.never().optional(),
                path: zFolderGetOnePath,
                query: z.never().optional()
            }).parseAsync(data),
            responseValidator: async (data) => await zFolderGetOneResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/folders/{folder_id}',
            ...options
        });
    }
}
