// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/py` | (string & {});
};

/**
 * AppSettingResponse
 *
 * Single app setting response.
 */
export type AppSettingResponse = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: {
        [key: string]: unknown;
    };
    /**
     * Updated By
     */
    updated_by: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ApplicationSettings
 */
export type ApplicationSettings = {
    /**
     * Llm Providers
     */
    llm_providers?: Array<LlmProvider>;
};

/**
 * ChatSessionInfo
 */
export type ChatSessionInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Folder Id
     */
    folder_id: string | unknown;
    /**
     * System Prompt
     */
    system_prompt: string | unknown;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ChatSessionInfoList
 */
export type ChatSessionInfoList = {
    /**
     * Sessions
     */
    sessions: Array<ChatSessionInfo>;
};

/**
 * ChatSessionModel
 */
export type ChatSessionModel = {
    info: ChatSessionInfo;
    /**
     * Messages
     */
    messages: Array<MessageModel>;
};

/**
 * ChatSessionUpdate
 */
export type ChatSessionUpdate = {
    /**
     * Title
     */
    title?: unknown;
    /**
     * Folder Id
     */
    folder_id?: unknown;
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: number;
};

/**
 * FolderModel
 */
export type FolderModel = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Parent Id
     */
    parent_id: string | unknown;
    /**
     * Sessions
     */
    sessions?: Array<ChatSessionInfo>;
    /**
     * Children
     */
    children?: Array<FolderModel>;
};

/**
 * FolderModelList
 */
export type FolderModelList = {
    /**
     * Folders
     */
    folders: Array<FolderModel>;
};

export type JsonValue = unknown;

/**
 * LLMProvider
 */
export type LlmProvider = {
    /**
     * Name
     */
    name: string;
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Models
     */
    models: Array<string>;
};

/**
 * MessageModel
 */
export type MessageModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Thinking
     */
    thinking: string;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Active Child Id
     */
    active_child_id: string | null;
    /**
     * Has Siblings
     */
    has_siblings?: boolean;
    /**
     * Sibling Count
     */
    sibling_count?: number;
    /**
     * Current Sibling Index
     */
    current_sibling_index?: number;
};

/**
 * NewChatSessionRequest
 */
export type NewChatSessionRequest = {
    /**
     * Folder Id
     */
    folder_id: string | null;
};

/**
 * NewFolderRequest
 */
export type NewFolderRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
};

/**
 * UpdateAppSettingRequest
 *
 * Update a single app setting by key (admin only).
 */
export type UpdateAppSettingRequest = {
    /**
     * Key
     */
    key: string;
    value: JsonValue;
};

/**
 * UpdateUserSettingRequest
 *
 * Update a single user setting by key.
 */
export type UpdateUserSettingRequest = {
    value: JsonValue;
};

/**
 * UserSettingResponse
 *
 * Single user setting response.
 */
export type UserSettingResponse = {
    /**
     * Key
     */
    key: string;
    value: JsonValue;
};

/**
 * UserSettings
 *
 * Aggregated view of all user settings.
 */
export type UserSettings = {
    /**
     * Theme
     */
    theme?: string;
    /**
     * Font Size
     */
    font_size?: string;
};

export type GetFileData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/files/{filename}';
};

export type GetFileErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
    /**
     * Returns the user's file
     */
    200: Blob | File;
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type ChatSessionGetManyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chat/';
};

export type ChatSessionGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type ChatSessionGetManyError = ChatSessionGetManyErrors[keyof ChatSessionGetManyErrors];

export type ChatSessionGetManyResponses = {
    /**
     * Successful Response
     */
    200: ChatSessionInfoList;
};

export type ChatSessionGetManyResponse = ChatSessionGetManyResponses[keyof ChatSessionGetManyResponses];

export type ChatSessionCreateData = {
    body: NewChatSessionRequest;
    path?: never;
    query?: never;
    url: '/chat/';
};

export type ChatSessionCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionCreateError = ChatSessionCreateErrors[keyof ChatSessionCreateErrors];

export type ChatSessionCreateResponses = {
    /**
     * Successful Response
     */
    200: ChatSessionModel;
};

export type ChatSessionCreateResponse = ChatSessionCreateResponses[keyof ChatSessionCreateResponses];

export type ChatSessionGetOneData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/chat/{session_id}';
};

export type ChatSessionGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionGetOneError = ChatSessionGetOneErrors[keyof ChatSessionGetOneErrors];

export type ChatSessionGetOneResponses = {
    /**
     * Successful Response
     */
    200: ChatSessionModel;
};

export type ChatSessionGetOneResponse = ChatSessionGetOneResponses[keyof ChatSessionGetOneResponses];

export type ChatSessionDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/chat/{session_id}';
};

export type ChatSessionDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionDeleteError = ChatSessionDeleteErrors[keyof ChatSessionDeleteErrors];

export type ChatSessionDeleteResponses = {
    /**
     * Successful Response
     */
    200: ChatSessionModel;
};

export type ChatSessionDeleteResponse = ChatSessionDeleteResponses[keyof ChatSessionDeleteResponses];

export type ChatSessionUpdateData = {
    body: ChatSessionUpdate;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/chat/{session_id}';
};

export type ChatSessionUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionUpdateError = ChatSessionUpdateErrors[keyof ChatSessionUpdateErrors];

export type ChatSessionUpdateResponses = {
    /**
     * Successful Response
     */
    200: ChatSessionModel;
};

export type ChatSessionUpdateResponse = ChatSessionUpdateResponses[keyof ChatSessionUpdateResponses];

export type FolderGetManyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/folders/';
};

export type FolderGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type FolderGetManyError = FolderGetManyErrors[keyof FolderGetManyErrors];

export type FolderGetManyResponses = {
    /**
     * Successful Response
     */
    200: FolderModelList;
};

export type FolderGetManyResponse = FolderGetManyResponses[keyof FolderGetManyResponses];

export type FolderCreateData = {
    body: NewFolderRequest;
    path?: never;
    query?: never;
    url: '/folders/';
};

export type FolderCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderCreateError = FolderCreateErrors[keyof FolderCreateErrors];

export type FolderCreateResponses = {
    /**
     * Successful Response
     */
    200: FolderModel;
};

export type FolderCreateResponse = FolderCreateResponses[keyof FolderCreateResponses];

export type FolderDeleteData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/folders/{folder_id}';
};

export type FolderDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderDeleteError = FolderDeleteErrors[keyof FolderDeleteErrors];

export type FolderDeleteResponses = {
    /**
     * Successful Response
     */
    200: FolderModel;
};

export type FolderDeleteResponse = FolderDeleteResponses[keyof FolderDeleteResponses];

export type FolderGetOneData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/folders/{folder_id}';
};

export type FolderGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderGetOneError = FolderGetOneErrors[keyof FolderGetOneErrors];

export type FolderGetOneResponses = {
    /**
     * Successful Response
     */
    200: FolderModel;
};

export type FolderGetOneResponse = FolderGetOneResponses[keyof FolderGetOneResponses];

export type UserSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/user';
};

export type UserSettingsGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type UserSettingsGetError = UserSettingsGetErrors[keyof UserSettingsGetErrors];

export type UserSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UserSettingsGetResponse = UserSettingsGetResponses[keyof UserSettingsGetResponses];

export type UserSettingsBulkUpdateData = {
    /**
     * Updates
     */
    body: {
        [key: string]: JsonValue;
    };
    path?: never;
    query?: never;
    url: '/settings/user';
};

export type UserSettingsBulkUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingsBulkUpdateError = UserSettingsBulkUpdateErrors[keyof UserSettingsBulkUpdateErrors];

export type UserSettingsBulkUpdateResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UserSettingsBulkUpdateResponse = UserSettingsBulkUpdateResponses[keyof UserSettingsBulkUpdateResponses];

export type UserSettingDeleteData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/user/{key}';
};

export type UserSettingDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingDeleteError = UserSettingDeleteErrors[keyof UserSettingDeleteErrors];

export type UserSettingDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UserSettingUpdateData = {
    body: UpdateUserSettingRequest;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/user/{key}';
};

export type UserSettingUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingUpdateError = UserSettingUpdateErrors[keyof UserSettingUpdateErrors];

export type UserSettingUpdateResponses = {
    /**
     * Successful Response
     */
    200: UserSettingResponse;
};

export type UserSettingUpdateResponse = UserSettingUpdateResponses[keyof UserSettingUpdateResponses];

export type AppSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/app';
};

export type AppSettingsGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AppSettingsGetError = AppSettingsGetErrors[keyof AppSettingsGetErrors];

export type AppSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: ApplicationSettings;
};

export type AppSettingsGetResponse = AppSettingsGetResponses[keyof AppSettingsGetResponses];

export type AppSettingsBulkUpdateData = {
    /**
     * Updates
     */
    body: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
    path?: never;
    query?: never;
    url: '/settings/app';
};

export type AppSettingsBulkUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingsBulkUpdateError = AppSettingsBulkUpdateErrors[keyof AppSettingsBulkUpdateErrors];

export type AppSettingsBulkUpdateResponses = {
    /**
     * Successful Response
     */
    200: ApplicationSettings;
};

export type AppSettingsBulkUpdateResponse = AppSettingsBulkUpdateResponses[keyof AppSettingsBulkUpdateResponses];

export type AppSettingDeleteData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/app/{key}';
};

export type AppSettingDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingDeleteError = AppSettingDeleteErrors[keyof AppSettingDeleteErrors];

export type AppSettingDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AppSettingGetData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/app/{key}';
};

export type AppSettingGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingGetError = AppSettingGetErrors[keyof AppSettingGetErrors];

export type AppSettingGetResponses = {
    /**
     * Successful Response
     */
    200: AppSettingResponse;
};

export type AppSettingGetResponse = AppSettingGetResponses[keyof AppSettingGetResponses];

export type AppSettingUpdateData = {
    body: UpdateAppSettingRequest;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/app/{key}';
};

export type AppSettingUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingUpdateError = AppSettingUpdateErrors[keyof AppSettingUpdateErrors];

export type AppSettingUpdateResponses = {
    /**
     * Successful Response
     */
    200: AppSettingResponse;
};

export type AppSettingUpdateResponse = AppSettingUpdateResponses[keyof AppSettingUpdateResponses];
