// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/py` | (string & {});
};

/**
 * ApplicationSettings
 */
export type ApplicationSettings = {
    /**
     * Llm Providers
     */
    llm_providers?: Array<LlmProvider>;
};

/**
 * ChatInfo
 */
export type ChatInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
};

/**
 * ChatModel
 */
export type ChatModel = {
    info: ChatInfo;
    /**
     * Messages
     */
    messages: Array<MessageModel>;
};

/**
 * ChatModelList
 */
export type ChatModelList = {
    /**
     * Chats
     */
    chats: Array<ChatInfo>;
};

/**
 * ChatUpdateRequest
 */
export type ChatUpdateRequest = {
    /**
     * Title
     */
    title?: unknown;
    /**
     * Folder Id
     */
    folder_id?: unknown;
};

/**
 * CreateUserRequest
 */
export type CreateUserRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * System Key
     */
    system_key?: string | null;
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: number;
};

/**
 * FolderModel
 */
export type FolderModel = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Parent Id
     */
    parent_id: string | unknown;
    /**
     * Sessions
     */
    sessions?: Array<ChatInfo>;
    /**
     * Children
     */
    children?: Array<FolderModel>;
};

/**
 * FolderModelList
 */
export type FolderModelList = {
    /**
     * Folders
     */
    folders: Array<FolderModel>;
};

/**
 * Function
 */
export type Function = {
    /**
     * Name
     */
    name: string;
    /**
     * Arguments
     */
    arguments: string;
};

export type JsonValue = unknown;

/**
 * LLMProvider
 */
export type LlmProvider = {
    /**
     * Name
     */
    name: string;
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Models
     */
    models: Array<string>;
};

/**
 * MessageModel
 */
export type MessageModel = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Token Count
     */
    token_count: number;
    /**
     * Thinking
     */
    thinking?: string | null;
    /**
     * Tool Calls
     */
    tool_calls?: Array<ToolCall> | null;
    /**
     * Tool Call Id
     */
    tool_call_id?: string | null;
    /**
     * Id
     */
    id: string;
    status: MessageStatus;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Active Child Id
     */
    active_child_id: string | null;
    /**
     * Has Siblings
     */
    has_siblings?: boolean;
    /**
     * Sibling Count
     */
    sibling_count?: number;
    /**
     * Current Sibling Index
     */
    current_sibling_index?: number;
};

/**
 * MessageStatus
 */
export type MessageStatus = 'pending' | 'completed';

/**
 * NewChatRequest
 */
export type NewChatRequest = {
    /**
     * User Prompt
     */
    user_prompt: string;
    /**
     * Folder Id
     */
    folder_id?: unknown;
};

/**
 * NewFolderRequest
 */
export type NewFolderRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
};

/**
 * Setting
 */
export type Setting = {
    /**
     * Key
     */
    key: string;
    value: JsonValue;
};

/**
 * ToolCall
 */
export type ToolCall = {
    /**
     * Id
     */
    id: string;
    function: Function;
    /**
     * Type
     */
    type?: string;
};

/**
 * UpdateSettingValue
 */
export type UpdateSettingValue = {
    value: JsonValue;
};

/**
 * UserSettings
 */
export type UserSettings = {
    /**
     * Theme
     */
    theme?: string;
    /**
     * Font Size
     */
    font_size?: string;
};

export type GetFileData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/files/{filename}';
};

export type GetFileErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
    /**
     * Returns the user's file
     */
    200: Blob | File;
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type ChatSessionGetManyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chat/';
};

export type ChatSessionGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type ChatSessionGetManyError = ChatSessionGetManyErrors[keyof ChatSessionGetManyErrors];

export type ChatSessionGetManyResponses = {
    /**
     * Successful Response
     */
    200: ChatModelList;
};

export type ChatSessionGetManyResponse = ChatSessionGetManyResponses[keyof ChatSessionGetManyResponses];

export type ChatSessionCreateData = {
    body: NewChatRequest;
    path?: never;
    query?: never;
    url: '/chat/';
};

export type ChatSessionCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionCreateError = ChatSessionCreateErrors[keyof ChatSessionCreateErrors];

export type ChatSessionCreateResponses = {
    /**
     * Successful Response
     */
    200: ChatModel;
};

export type ChatSessionCreateResponse = ChatSessionCreateResponses[keyof ChatSessionCreateResponses];

export type ChatSessionGetOneData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/chat/{session_id}';
};

export type ChatSessionGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionGetOneError = ChatSessionGetOneErrors[keyof ChatSessionGetOneErrors];

export type ChatSessionGetOneResponses = {
    /**
     * Successful Response
     */
    200: ChatModel;
};

export type ChatSessionGetOneResponse = ChatSessionGetOneResponses[keyof ChatSessionGetOneResponses];

export type ChatSessionDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/chat/{session_id}';
};

export type ChatSessionDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionDeleteError = ChatSessionDeleteErrors[keyof ChatSessionDeleteErrors];

export type ChatSessionDeleteResponses = {
    /**
     * Successful Response
     */
    200: ChatModel;
};

export type ChatSessionDeleteResponse = ChatSessionDeleteResponses[keyof ChatSessionDeleteResponses];

export type ChatSessionUpdateData = {
    body: ChatUpdateRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/chat/{session_id}';
};

export type ChatSessionUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionUpdateError = ChatSessionUpdateErrors[keyof ChatSessionUpdateErrors];

export type ChatSessionUpdateResponses = {
    /**
     * Successful Response
     */
    200: ChatModel;
};

export type ChatSessionUpdateResponse = ChatSessionUpdateResponses[keyof ChatSessionUpdateResponses];

export type FolderGetManyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/folders/';
};

export type FolderGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type FolderGetManyError = FolderGetManyErrors[keyof FolderGetManyErrors];

export type FolderGetManyResponses = {
    /**
     * Successful Response
     */
    200: FolderModelList;
};

export type FolderGetManyResponse = FolderGetManyResponses[keyof FolderGetManyResponses];

export type FolderCreateData = {
    body: NewFolderRequest;
    path?: never;
    query?: never;
    url: '/folders/';
};

export type FolderCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderCreateError = FolderCreateErrors[keyof FolderCreateErrors];

export type FolderCreateResponses = {
    /**
     * Successful Response
     */
    200: FolderModel;
};

export type FolderCreateResponse = FolderCreateResponses[keyof FolderCreateResponses];

export type FolderDeleteData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/folders/{folder_id}';
};

export type FolderDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderDeleteError = FolderDeleteErrors[keyof FolderDeleteErrors];

export type FolderDeleteResponses = {
    /**
     * Successful Response
     */
    200: FolderModel;
};

export type FolderDeleteResponse = FolderDeleteResponses[keyof FolderDeleteResponses];

export type FolderGetOneData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/folders/{folder_id}';
};

export type FolderGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderGetOneError = FolderGetOneErrors[keyof FolderGetOneErrors];

export type FolderGetOneResponses = {
    /**
     * Successful Response
     */
    200: FolderModel;
};

export type FolderGetOneResponse = FolderGetOneResponses[keyof FolderGetOneResponses];

export type UserSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/user';
};

export type UserSettingsGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type UserSettingsGetError = UserSettingsGetErrors[keyof UserSettingsGetErrors];

export type UserSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UserSettingsGetResponse = UserSettingsGetResponses[keyof UserSettingsGetResponses];

export type UserSettingsBulkUpdateData = {
    /**
     * Updates
     */
    body: {
        [key: string]: JsonValue;
    };
    path?: never;
    query?: never;
    url: '/settings/user';
};

export type UserSettingsBulkUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingsBulkUpdateError = UserSettingsBulkUpdateErrors[keyof UserSettingsBulkUpdateErrors];

export type UserSettingsBulkUpdateResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UserSettingsBulkUpdateResponse = UserSettingsBulkUpdateResponses[keyof UserSettingsBulkUpdateResponses];

export type UserSettingDeleteData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/user/{key}';
};

export type UserSettingDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingDeleteError = UserSettingDeleteErrors[keyof UserSettingDeleteErrors];

export type UserSettingDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UserSettingUpdateData = {
    body: UpdateSettingValue;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/user/{key}';
};

export type UserSettingUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingUpdateError = UserSettingUpdateErrors[keyof UserSettingUpdateErrors];

export type UserSettingUpdateResponses = {
    /**
     * Successful Response
     */
    200: Setting;
};

export type UserSettingUpdateResponse = UserSettingUpdateResponses[keyof UserSettingUpdateResponses];

export type AppSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/app';
};

export type AppSettingsGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AppSettingsGetError = AppSettingsGetErrors[keyof AppSettingsGetErrors];

export type AppSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: ApplicationSettings;
};

export type AppSettingsGetResponse = AppSettingsGetResponses[keyof AppSettingsGetResponses];

export type AppSettingsBulkUpdateData = {
    /**
     * Updates
     */
    body: {
        [key: string]: JsonValue;
    };
    path?: never;
    query?: never;
    url: '/settings/app';
};

export type AppSettingsBulkUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingsBulkUpdateError = AppSettingsBulkUpdateErrors[keyof AppSettingsBulkUpdateErrors];

export type AppSettingsBulkUpdateResponses = {
    /**
     * Successful Response
     */
    200: ApplicationSettings;
};

export type AppSettingsBulkUpdateResponse = AppSettingsBulkUpdateResponses[keyof AppSettingsBulkUpdateResponses];

export type AppSettingDeleteData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/app/{key}';
};

export type AppSettingDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingDeleteError = AppSettingDeleteErrors[keyof AppSettingDeleteErrors];

export type AppSettingDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AppSettingUpdateData = {
    body: UpdateSettingValue;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/app/{key}';
};

export type AppSettingUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingUpdateError = AppSettingUpdateErrors[keyof AppSettingUpdateErrors];

export type AppSettingUpdateResponses = {
    /**
     * Successful Response
     */
    200: Setting;
};

export type AppSettingUpdateResponse = AppSettingUpdateResponses[keyof AppSettingUpdateResponses];

export type UserCreateUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users/';
};

export type UserCreateUserErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserCreateUserError = UserCreateUserErrors[keyof UserCreateUserErrors];

export type UserCreateUserResponses = {
    /**
     * Response Usercreateuser
     *
     * Successful Response
     */
    200: boolean;
};

export type UserCreateUserResponse = UserCreateUserResponses[keyof UserCreateUserResponses];

export type UserSettingDelete2Data = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UserSettingDelete2Errors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingDelete2Error = UserSettingDelete2Errors[keyof UserSettingDelete2Errors];

export type UserSettingDelete2Responses = {
    /**
     * Successful Response
     */
    200: unknown;
};
