// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/py` | (string & {});
};

/**
 * AgentProfile
 */
export type AgentProfile = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Sub Agent
     */
    sub_agent: boolean;
    /**
     * Model Id
     */
    model_id: string | null;
    /**
     * System Prompt
     */
    system_prompt: string | null;
    /**
     * Max Steps
     */
    max_steps: number;
    chat_parameters?: ChatCompletionParams;
    /**
     * Tools
     */
    tools?: Array<string> | null;
    /**
     * Id
     */
    id?: string;
    /**
     * Knowledge Bases
     */
    knowledge_bases?: Array<KnowledgeBaseAssignmentSummary>;
};

/**
 * ApplicationSettings
 */
export type ApplicationSettings = {
    /**
     * Llm Providers
     */
    llm_providers?: Array<Provider>;
    /**
     * Draft Model Id
     */
    draft_model_id?: string | null;
    web_search_provider?: ComponentProviderParameters | null;
    image_search_provider?: ComponentProviderParameters | null;
    /**
     * Active Tools
     */
    active_tools: Array<string>;
};

/**
 * Body_fileUpload
 */
export type BodyFileUpload = {
    /**
     * Files
     *
     * Files to upload
     */
    files: Array<Blob | File>;
};

/**
 * BulkDeleteChatRequest
 */
export type BulkDeleteChatRequest = {
    /**
     * Chat Ids
     */
    chat_ids: Array<string>;
};

/**
 * BulkDeleteChatResponse
 */
export type BulkDeleteChatResponse = {
    /**
     * Deleted Chat Ids
     */
    deleted_chat_ids: Array<string>;
};

/**
 * BulkUpdateSettingRequest
 */
export type BulkUpdateSettingRequest = {
    /**
     * Values
     */
    values: {
        [key: string]: JsonValue;
    };
};

/**
 * CaptionModelStatus
 *
 * Admin-facing status of the local caption model download/readiness.
 */
export type CaptionModelStatus = {
    status: DownloadStatus;
    /**
     * Bytes Downloaded
     */
    bytes_downloaded?: number;
    /**
     * Total Bytes
     */
    total_bytes?: number;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Bundle Sha256
     */
    bundle_sha256?: string | null;
};

/**
 * Chat
 */
export type Chat = {
    info: ChatInfo;
    /**
     * Messages
     */
    messages: Array<Message>;
    context_usage?: ChatContextUsage | null;
};

/**
 * ChatCompletionParams
 */
export type ChatCompletionParams = {
    /**
     * Reasoning Effort
     */
    reasoning_effort?: unknown;
    /**
     * Temperature
     */
    temperature?: number;
    /**
     * Top P
     */
    top_p?: number;
    /**
     * Frequency Penalty
     */
    frequency_penalty?: number;
    /**
     * Presence Penalty
     */
    presence_penalty?: number;
    /**
     * Seed
     */
    seed?: number;
    /**
     * Stop
     */
    stop?: string | Array<string>;
    /**
     * Extra Body
     */
    extra_body?: {
        [key: string]: unknown;
    };
    /**
     * Tool Choice
     */
    tool_choice?: 'required' | 'auto' | 'none' | {
        [key: string]: unknown;
    };
    /**
     * Max Tokens
     */
    max_tokens?: number;
    /**
     * Modalities
     */
    modalities?: Array<'text' | 'audio'>;
    /**
     * Audio
     */
    audio?: {
        [key: string]: unknown;
    };
    /**
     * Prediction
     */
    prediction?: {
        [key: string]: unknown;
    };
    /**
     * Parallel Tool Calls
     */
    parallel_tool_calls?: boolean;
    /**
     * N
     */
    n?: number;
    /**
     * Logit Bias
     */
    logit_bias?: {
        [key: string]: number;
    };
    /**
     * Logprobs
     */
    logprobs?: boolean;
    /**
     * Top Logprobs
     */
    top_logprobs?: number;
    /**
     * Extra Headers
     */
    extra_headers?: {
        [key: string]: string;
    };
    /**
     * Extra Query
     */
    extra_query?: {
        [key: string]: unknown;
    };
    /**
     * Timeout
     */
    timeout?: number | null;
};

/**
 * ChatContextModel
 */
export type ChatContextModel = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Context Window
     */
    context_window?: number | null;
    context_window_source?: ModelCapabilitySource;
};

/**
 * ChatContextUsage
 */
export type ChatContextUsage = {
    /**
     * Input Tokens
     */
    input_tokens: number;
    /**
     * Reserved Output Tokens
     */
    reserved_output_tokens?: number | null;
    /**
     * Total Tokens
     */
    total_tokens: number;
    /**
     * Estimated
     */
    estimated?: boolean;
};

/**
 * ChatInfo
 */
export type ChatInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Allowed Tools
     */
    allowed_tools?: Array<string>;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Preview
     */
    preview?: string | null;
    /**
     * Message Count
     */
    message_count?: number | null;
    context_model?: ChatContextModel | null;
};

/**
 * ChatInfoList
 */
export type ChatInfoList = {
    /**
     * Chats
     */
    chats: Array<ChatInfo>;
};

/**
 * ChatUpdateRequest
 */
export type ChatUpdateRequest = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
};

/**
 * ComponentListResponse
 */
export type ComponentListResponse = {
    /**
     * Items
     */
    items: Array<ComponentResponse>;
};

/**
 * ComponentProviderParameters
 */
export type ComponentProviderParameters = {
    /**
     * Name
     */
    name: string;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: string;
    };
};

/**
 * ComponentResponse
 */
export type ComponentResponse = {
    /**
     * Type
     */
    type: string;
    /**
     * Name
     */
    name: string;
    /**
     * Parameters
     */
    parameters: {
        [key: string]: unknown;
    };
};

/**
 * ComponentType
 */
export type ComponentType = 'WebSearch' | 'ImageSearch' | 'ImageGenerator';

/**
 * CreateUserRequest
 *
 * Request model for creating a new user.
 */
export type CreateUserRequest = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * System Key
     *
     * Optional system key for user creation.
     */
    system_key?: string | null;
};

/**
 * DownloadStatus
 */
export type DownloadStatus = 'idle' | 'downloading' | 'verifying' | 'ready' | 'failed';

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: number;
};

/**
 * FileContentStatus
 */
export type FileContentStatus = 'pending' | 'ready' | 'unsupported' | 'failed';

/**
 * FileKind
 */
export type FileKind = 'image' | 'text' | 'document' | 'other';

/**
 * Folder
 */
export type Folder = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Sessions
     */
    sessions?: Array<ChatInfo>;
    /**
     * Children
     */
    children?: Array<Folder>;
};

/**
 * FolderChatList
 */
export type FolderChatList = {
    /**
     * Chats
     */
    chats: Array<ChatInfo>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * FolderList
 */
export type FolderList = {
    /**
     * Folders
     */
    folders: Array<Folder>;
};

/**
 * Function
 */
export type Function = {
    /**
     * Name
     */
    name: string;
    /**
     * Arguments
     */
    arguments: string;
};

export type JsonValue = unknown;

/**
 * KnowledgeBase
 */
export type KnowledgeBase = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
};

/**
 * KnowledgeBaseAssignmentList
 */
export type KnowledgeBaseAssignmentList = {
    /**
     * Knowledge Base Ids
     */
    knowledge_base_ids: Array<string>;
};

/**
 * KnowledgeBaseAssignmentReplace
 */
export type KnowledgeBaseAssignmentReplace = {
    /**
     * Knowledge Base Ids
     */
    knowledge_base_ids?: Array<string>;
};

/**
 * KnowledgeBaseAssignmentSummary
 */
export type KnowledgeBaseAssignmentSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * KnowledgeBaseCreate
 */
export type KnowledgeBaseCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * KnowledgeBaseList
 */
export type KnowledgeBaseList = {
    /**
     * Knowledge Bases
     */
    knowledge_bases: Array<KnowledgeBase>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * KnowledgeBaseUpdate
 */
export type KnowledgeBaseUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * KnowledgeCaptionConfiguration
 */
export type KnowledgeCaptionConfiguration = {
    /**
     * Mode
     */
    mode: string;
    /**
     * Provider Model Id
     */
    provider_model_id: string | null;
    /**
     * Updated At
     */
    updated_at: number;
};

/**
 * KnowledgeCaptionConfigurationUpdate
 */
export type KnowledgeCaptionConfigurationUpdate = {
    /**
     * Mode
     */
    mode: string;
    /**
     * Provider Model Id
     */
    provider_model_id?: string | null;
};

/**
 * KnowledgeCaptionMetadata
 */
export type KnowledgeCaptionMetadata = {
    /**
     * Status
     */
    status?: string | null;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Error Reason
     */
    error_reason?: string | null;
    /**
     * Generated At
     */
    generated_at?: number | null;
    /**
     * Accepted At
     */
    accepted_at?: number | null;
};

/**
 * KnowledgeCaptionUpdate
 */
export type KnowledgeCaptionUpdate = {
    /**
     * Text
     */
    text?: string | null;
    /**
     * Accept
     */
    accept?: boolean;
    /**
     * Clear
     */
    clear?: boolean;
};

/**
 * KnowledgeDocument
 */
export type KnowledgeDocument = {
    /**
     * Id
     */
    id: string;
    /**
     * Knowledge Base Id
     */
    knowledge_base_id: string;
    /**
     * File Id
     */
    file_id: string | null;
    /**
     * Original Name
     */
    original_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Content Sha256
     */
    content_sha256: string;
    /**
     * Revision
     */
    revision: number;
    /**
     * Position
     */
    position: number;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error: string | null;
    /**
     * Indexed At
     */
    indexed_at: number | null;
    /**
     * Replaces Document Id
     */
    replaces_document_id: string | null;
    caption: KnowledgeCaptionMetadata;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: string;
    };
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
};

/**
 * KnowledgeDocumentCreate
 */
export type KnowledgeDocumentCreate = {
    /**
     * File Id
     */
    file_id: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    };
};

/**
 * KnowledgeDocumentList
 */
export type KnowledgeDocumentList = {
    /**
     * Documents
     */
    documents: Array<KnowledgeDocument>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * KnowledgeDocumentRevisionCreate
 */
export type KnowledgeDocumentRevisionCreate = {
    /**
     * File Id
     */
    file_id: string;
    /**
     * Metadata
     */
    metadata?: {
        [key: string]: string;
    } | null;
};

/**
 * KnowledgeDocumentUpdate
 */
export type KnowledgeDocumentUpdate = {
    /**
     * Metadata
     */
    metadata: {
        [key: string]: string;
    };
};

/**
 * Llm
 */
export type Llm = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Provider Id
     */
    provider_id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Context Window
     */
    context_window?: number | null;
    /**
     * Supports Vision
     */
    supports_vision?: boolean | null;
    context_window_source?: ModelCapabilitySource;
    vision_source?: ModelCapabilitySource;
};

/**
 * LlmDisplayInfo
 */
export type LlmDisplayInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Provider Id
     */
    provider_id: string;
    /**
     * Provider Name
     */
    provider_name: string;
    /**
     * Context Window
     */
    context_window?: number | null;
    /**
     * Supports Vision
     */
    supports_vision?: boolean | null;
    context_window_source?: ModelCapabilitySource;
    vision_source?: ModelCapabilitySource;
};

/**
 * Message
 */
export type Message = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Thinking
     */
    thinking?: string | null;
    /**
     * Tool Calls
     */
    tool_calls?: Array<ToolCall> | null;
    /**
     * Id
     */
    id: string;
    status: MessageStatus;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Model Id
     */
    model_id?: string | null;
    /**
     * Input Tokens
     */
    input_tokens?: number;
    /**
     * Output Tokens
     */
    output_tokens?: number;
    /**
     * Total Tokens
     */
    total_tokens?: number;
    /**
     * Generation Duration Ms
     */
    generation_duration_ms?: number;
    /**
     * Tool Call Results
     */
    tool_call_results?: Array<ToolResult> | null;
    /**
     * Files
     */
    files?: Array<MessageFileReference>;
    /**
     * Active Child Id
     */
    active_child_id?: string | null;
    /**
     * Has Siblings
     */
    has_siblings?: boolean;
    /**
     * Sibling Count
     */
    sibling_count?: number;
    /**
     * Current Sibling Index
     */
    current_sibling_index?: number;
    /**
     * Parent Message Id
     */
    parent_message_id?: string | null;
    /**
     * Next Sibling Id
     */
    next_sibling_id?: string | null;
    /**
     * Previous Sibling Id
     */
    previous_sibling_id?: string | null;
};

/**
 * MessageFileReference
 */
export type MessageFileReference = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Name
     */
    name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size
     */
    size: number;
    kind: FileKind;
    status: FileContentStatus;
};

/**
 * MessageStatus
 */
export type MessageStatus = 'pending' | 'completed' | 'cancelled';

/**
 * ModelCapabilitySource
 */
export type ModelCapabilitySource = 'catalog' | 'provider' | 'manual' | 'unknown';

/**
 * NewChatRequest
 */
export type NewChatRequest = {
    /**
     * User Prompt
     */
    user_prompt: string;
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    /**
     * Files
     */
    files?: Array<string>;
};

/**
 * NewFolderRequest
 */
export type NewFolderRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * PartialAgentProfile
 */
export type PartialAgentProfile = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Sub Agent
     */
    sub_agent: boolean;
    /**
     * Model Id
     */
    model_id: string | null;
    /**
     * System Prompt
     */
    system_prompt: string | null;
    /**
     * Max Steps
     */
    max_steps: number;
    chat_parameters?: ChatCompletionParams;
    /**
     * Tools
     */
    tools?: Array<string> | null;
    /**
     * Id
     */
    id?: string | null;
};

/**
 * Provider
 */
export type Provider = {
    /**
     * Name
     */
    name: string;
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Id
     */
    id: string;
    provider_type?: ProviderType;
    /**
     * Models
     */
    models: Array<Llm>;
};

/**
 * ProviderDiscoveryRequest
 */
export type ProviderDiscoveryRequest = {
    provider_type: ProviderType;
    /**
     * Base Url
     */
    base_url?: string;
    /**
     * Provider Id
     */
    provider_id: string;
    /**
     * Existing Models
     */
    existing_models?: Array<Llm>;
    /**
     * Draft Model Id
     */
    draft_model_id?: string | null;
};

/**
 * ProviderDiscoveryResponse
 */
export type ProviderDiscoveryResponse = {
    /**
     * Models
     */
    models: Array<Llm>;
    /**
     * Catalog Version
     */
    catalog_version?: string | null;
    /**
     * Warnings
     */
    warnings?: Array<string>;
};

/**
 * ProviderType
 */
export type ProviderType = 'openai' | 'generic_openai';

/**
 * SearchMatchSource
 */
export type SearchMatchSource = 'title' | 'content' | 'folder_title';

/**
 * SearchResult
 */
export type SearchResult = {
    kind: SearchResultKind;
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: number;
    /**
     * Folder Id
     */
    folder_id?: string | null;
    match_source: SearchMatchSource;
    /**
     * Snippet
     */
    snippet?: string | null;
    /**
     * Path
     */
    path?: Array<string>;
};

/**
 * SearchResultKind
 */
export type SearchResultKind = 'chat' | 'folder';

/**
 * SearchResultList
 */
export type SearchResultList = {
    /**
     * Results
     */
    results: Array<SearchResult>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * Setting
 */
export type Setting = {
    /**
     * Key
     */
    key: string;
    value: JsonValue;
};

/**
 * SubAgentTrace
 */
export type SubAgentTrace = {
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: number;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Parent Message Id
     */
    parent_message_id?: string | null;
    /**
     * Sub Agent Id
     */
    sub_agent_id: string;
    /**
     * Sub Agent Name
     */
    sub_agent_name: string;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Caller Context
     */
    caller_context?: string | null;
    /**
     * Messages
     */
    messages?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Result
     */
    result?: string | null;
    /**
     * Step Count
     */
    step_count?: number;
    /**
     * Total Tokens
     */
    total_tokens?: number;
    /**
     * Elapsed Ms
     */
    elapsed_ms?: number;
    /**
     * Depth
     */
    depth?: number;
};

/**
 * ToolCall
 */
export type ToolCall = {
    /**
     * Id
     */
    id: string;
    function: Function;
    /**
     * Type
     */
    type?: 'function';
};

/**
 * ToolInfo
 */
export type ToolInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    component_type?: ComponentType | null;
};

/**
 * ToolInfoList
 */
export type ToolInfoList = {
    /**
     * Items
     */
    items: Array<ToolInfo>;
};

/**
 * ToolResult
 */
export type ToolResult = {
    /**
     * Content
     */
    content: string;
    /**
     * Raw Result
     */
    raw_result: unknown;
    /**
     * Is Empty
     */
    is_empty: boolean;
    tool_call: ToolCall;
};

/**
 * UpdateMessageRequest
 */
export type UpdateMessageRequest = {
    /**
     * Content
     */
    content?: string | null;
    /**
     * Thinking
     */
    thinking?: string | null;
    /**
     * Active Child Id
     */
    active_child_id?: string | null;
    status?: MessageStatus | null;
    /**
     * Tool Results
     */
    tool_results?: Array<ToolResult> | null;
};

/**
 * UpdateSettingValue
 */
export type UpdateSettingValue = {
    value: JsonValue;
};

/**
 * UserAgents
 */
export type UserAgents = {
    /**
     * Agents
     */
    agents: {
        [key: string]: AgentProfile;
    };
};

/**
 * UserFile
 */
export type UserFile = {
    /**
     * Id
     */
    id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Original Name
     */
    original_name: string;
    /**
     * Size
     */
    size: number;
    /**
     * Mime Type
     */
    mime_type: string;
    kind: FileKind;
    content_status: FileContentStatus;
    /**
     * Content Error
     */
    content_error: string | null;
    /**
     * Created At
     */
    created_at: number;
    /**
     * Updated At
     */
    updated_at: number;
};

/**
 * UserFileList
 */
export type UserFileList = {
    /**
     * Files
     */
    files: Array<UserFile>;
    /**
     * Total
     */
    total?: number;
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * UserSettings
 */
export type UserSettings = {
    /**
     * Theme
     */
    theme?: string;
    /**
     * Font Size
     */
    font_size?: string;
    /**
     * Models
     */
    models?: Array<LlmDisplayInfo>;
    /**
     * Default Model Id
     */
    default_model_id?: string | null;
    /**
     * Agents
     */
    agents?: {
        [key: string]: AgentProfile;
    };
    /**
     * Default Agent Id
     */
    default_agent_id?: string | null;
};

/**
 * ProviderDiscoveryRequest
 */
export type ProviderDiscoveryRequestWritable = {
    provider_type: ProviderType;
    /**
     * Base Url
     */
    base_url?: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Provider Id
     */
    provider_id: string;
    /**
     * Existing Models
     */
    existing_models?: Array<Llm>;
    /**
     * Draft Model Id
     */
    draft_model_id?: string | null;
};

export type FileGetManyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/files/';
};

export type FileGetManyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FileGetManyError = FileGetManyErrors[keyof FileGetManyErrors];

export type FileGetManyResponses = {
    /**
     * Successful Response
     */
    200: UserFileList;
};

export type FileGetManyResponse = FileGetManyResponses[keyof FileGetManyResponses];

export type FileUploadData = {
    body: BodyFileUpload;
    path?: never;
    query?: never;
    url: '/files/';
};

export type FileUploadErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FileUploadError = FileUploadErrors[keyof FileUploadErrors];

export type FileUploadResponses = {
    /**
     * Successful Response
     */
    201: UserFileList;
};

export type FileUploadResponse = FileUploadResponses[keyof FileUploadResponses];

export type FileDeleteData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/files/{filename}';
};

export type FileDeleteErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FileDeleteError = FileDeleteErrors[keyof FileDeleteErrors];

export type FileDeleteResponses = {
    /**
     * Successful Response
     */
    200: UserFile;
};

export type FileDeleteResponse = FileDeleteResponses[keyof FileDeleteResponses];

export type GetFileData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/files/{filename}';
};

export type GetFileErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
    /**
     * Returns the user's file
     */
    200: Blob | File;
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type ChatSessionGetManyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chat/';
};

export type ChatSessionGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type ChatSessionGetManyError = ChatSessionGetManyErrors[keyof ChatSessionGetManyErrors];

export type ChatSessionGetManyResponses = {
    /**
     * Successful Response
     */
    200: ChatInfoList;
};

export type ChatSessionGetManyResponse = ChatSessionGetManyResponses[keyof ChatSessionGetManyResponses];

export type ChatSessionCreateData = {
    body: NewChatRequest;
    path?: never;
    query?: never;
    url: '/chat/';
};

export type ChatSessionCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionCreateError = ChatSessionCreateErrors[keyof ChatSessionCreateErrors];

export type ChatSessionCreateResponses = {
    /**
     * Successful Response
     */
    200: Chat;
};

export type ChatSessionCreateResponse = ChatSessionCreateResponses[keyof ChatSessionCreateResponses];

export type ChatSessionBulkDeleteData = {
    body: BulkDeleteChatRequest;
    path?: never;
    query?: never;
    url: '/chat/bulk';
};

export type ChatSessionBulkDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionBulkDeleteError = ChatSessionBulkDeleteErrors[keyof ChatSessionBulkDeleteErrors];

export type ChatSessionBulkDeleteResponses = {
    /**
     * Successful Response
     */
    200: BulkDeleteChatResponse;
};

export type ChatSessionBulkDeleteResponse = ChatSessionBulkDeleteResponses[keyof ChatSessionBulkDeleteResponses];

export type ChatSessionDeleteData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}';
};

export type ChatSessionDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionDeleteError = ChatSessionDeleteErrors[keyof ChatSessionDeleteErrors];

export type ChatSessionDeleteResponses = {
    /**
     * Successful Response
     */
    200: Chat;
};

export type ChatSessionDeleteResponse = ChatSessionDeleteResponses[keyof ChatSessionDeleteResponses];

export type ChatSessionGetOneData = {
    body?: never;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}';
};

export type ChatSessionGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionGetOneError = ChatSessionGetOneErrors[keyof ChatSessionGetOneErrors];

export type ChatSessionGetOneResponses = {
    /**
     * Successful Response
     */
    200: Chat;
};

export type ChatSessionGetOneResponse = ChatSessionGetOneResponses[keyof ChatSessionGetOneResponses];

export type ChatSessionUpdateData = {
    body: ChatUpdateRequest;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}';
};

export type ChatSessionUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSessionUpdateError = ChatSessionUpdateErrors[keyof ChatSessionUpdateErrors];

export type ChatSessionUpdateResponses = {
    /**
     * Successful Response
     */
    200: Chat;
};

export type ChatSessionUpdateResponse = ChatSessionUpdateResponses[keyof ChatSessionUpdateResponses];

export type ChatSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/chat/search';
};

export type ChatSearchErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ChatSearchError = ChatSearchErrors[keyof ChatSearchErrors];

export type ChatSearchResponses = {
    /**
     * Successful Response
     */
    200: SearchResultList;
};

export type ChatSearchResponse = ChatSearchResponses[keyof ChatSearchResponses];

export type MessageUpdateData = {
    body: UpdateMessageRequest;
    path: {
        /**
         * Chat Id
         */
        chat_id: string;
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}/message/{message_id}';
};

export type MessageUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type MessageUpdateError = MessageUpdateErrors[keyof MessageUpdateErrors];

export type MessageUpdateResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type MessageUpdateResponse = MessageUpdateResponses[keyof MessageUpdateResponses];

export type FolderGetManyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/folders/';
};

export type FolderGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type FolderGetManyError = FolderGetManyErrors[keyof FolderGetManyErrors];

export type FolderGetManyResponses = {
    /**
     * Successful Response
     */
    200: FolderList;
};

export type FolderGetManyResponse = FolderGetManyResponses[keyof FolderGetManyResponses];

export type FolderCreateData = {
    body: NewFolderRequest;
    path?: never;
    query?: never;
    url: '/folders/';
};

export type FolderCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderCreateError = FolderCreateErrors[keyof FolderCreateErrors];

export type FolderCreateResponses = {
    /**
     * Successful Response
     */
    200: Folder;
};

export type FolderCreateResponse = FolderCreateResponses[keyof FolderCreateResponses];

export type FolderChatGetManyData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/folders/{folder_id}/chats';
};

export type FolderChatGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderChatGetManyError = FolderChatGetManyErrors[keyof FolderChatGetManyErrors];

export type FolderChatGetManyResponses = {
    /**
     * Successful Response
     */
    200: FolderChatList;
};

export type FolderChatGetManyResponse = FolderChatGetManyResponses[keyof FolderChatGetManyResponses];

export type FolderDeleteData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/folders/{folder_id}';
};

export type FolderDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderDeleteError = FolderDeleteErrors[keyof FolderDeleteErrors];

export type FolderDeleteResponses = {
    /**
     * Successful Response
     */
    200: Folder;
};

export type FolderDeleteResponse = FolderDeleteResponses[keyof FolderDeleteResponses];

export type FolderGetOneData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/folders/{folder_id}';
};

export type FolderGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type FolderGetOneError = FolderGetOneErrors[keyof FolderGetOneErrors];

export type FolderGetOneResponses = {
    /**
     * Successful Response
     */
    200: Folder;
};

export type FolderGetOneResponse = FolderGetOneResponses[keyof FolderGetOneResponses];

export type KnowledgeBaseGetManyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/knowledge-bases/';
};

export type KnowledgeBaseGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeBaseGetManyError = KnowledgeBaseGetManyErrors[keyof KnowledgeBaseGetManyErrors];

export type KnowledgeBaseGetManyResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBaseList;
};

export type KnowledgeBaseGetManyResponse = KnowledgeBaseGetManyResponses[keyof KnowledgeBaseGetManyResponses];

export type KnowledgeBaseCreateData = {
    body: KnowledgeBaseCreate;
    path?: never;
    query?: never;
    url: '/knowledge-bases/';
};

export type KnowledgeBaseCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Conflict
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeBaseCreateError = KnowledgeBaseCreateErrors[keyof KnowledgeBaseCreateErrors];

export type KnowledgeBaseCreateResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeBase;
};

export type KnowledgeBaseCreateResponse = KnowledgeBaseCreateResponses[keyof KnowledgeBaseCreateResponses];

export type KnowledgeDocumentGetManyData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/knowledge-bases/{knowledge_base_id}/documents';
};

export type KnowledgeDocumentGetManyErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentGetManyError = KnowledgeDocumentGetManyErrors[keyof KnowledgeDocumentGetManyErrors];

export type KnowledgeDocumentGetManyResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocumentList;
};

export type KnowledgeDocumentGetManyResponse = KnowledgeDocumentGetManyResponses[keyof KnowledgeDocumentGetManyResponses];

export type KnowledgeDocumentCreateData = {
    body: KnowledgeDocumentCreate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents';
};

export type KnowledgeDocumentCreateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Conflict
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentCreateError = KnowledgeDocumentCreateErrors[keyof KnowledgeDocumentCreateErrors];

export type KnowledgeDocumentCreateResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeDocument;
};

export type KnowledgeDocumentCreateResponse = KnowledgeDocumentCreateResponses[keyof KnowledgeDocumentCreateResponses];

export type KnowledgeDocumentCreateRevisionData = {
    body: KnowledgeDocumentRevisionCreate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}/revisions';
};

export type KnowledgeDocumentCreateRevisionErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Conflict
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentCreateRevisionError = KnowledgeDocumentCreateRevisionErrors[keyof KnowledgeDocumentCreateRevisionErrors];

export type KnowledgeDocumentCreateRevisionResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeDocument;
};

export type KnowledgeDocumentCreateRevisionResponse = KnowledgeDocumentCreateRevisionResponses[keyof KnowledgeDocumentCreateRevisionResponses];

export type KnowledgeDocumentDeleteData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}';
};

export type KnowledgeDocumentDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentDeleteError = KnowledgeDocumentDeleteErrors[keyof KnowledgeDocumentDeleteErrors];

export type KnowledgeDocumentDeleteResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocument;
};

export type KnowledgeDocumentDeleteResponse = KnowledgeDocumentDeleteResponses[keyof KnowledgeDocumentDeleteResponses];

export type KnowledgeDocumentGetOneData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}';
};

export type KnowledgeDocumentGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentGetOneError = KnowledgeDocumentGetOneErrors[keyof KnowledgeDocumentGetOneErrors];

export type KnowledgeDocumentGetOneResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocument;
};

export type KnowledgeDocumentGetOneResponse = KnowledgeDocumentGetOneResponses[keyof KnowledgeDocumentGetOneResponses];

export type KnowledgeDocumentUpdateMetadataData = {
    body: KnowledgeDocumentUpdate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}';
};

export type KnowledgeDocumentUpdateMetadataErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentUpdateMetadataError = KnowledgeDocumentUpdateMetadataErrors[keyof KnowledgeDocumentUpdateMetadataErrors];

export type KnowledgeDocumentUpdateMetadataResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocument;
};

export type KnowledgeDocumentUpdateMetadataResponse = KnowledgeDocumentUpdateMetadataResponses[keyof KnowledgeDocumentUpdateMetadataResponses];

export type KnowledgeDocumentUpdateCaptionData = {
    body: KnowledgeCaptionUpdate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}/caption';
};

export type KnowledgeDocumentUpdateCaptionErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentUpdateCaptionError = KnowledgeDocumentUpdateCaptionErrors[keyof KnowledgeDocumentUpdateCaptionErrors];

export type KnowledgeDocumentUpdateCaptionResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocument;
};

export type KnowledgeDocumentUpdateCaptionResponse = KnowledgeDocumentUpdateCaptionResponses[keyof KnowledgeDocumentUpdateCaptionResponses];

export type KnowledgeDocumentIngestData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}/ingest';
};

export type KnowledgeDocumentIngestErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentIngestError = KnowledgeDocumentIngestErrors[keyof KnowledgeDocumentIngestErrors];

export type KnowledgeDocumentIngestResponses = {
    /**
     * Successful Response
     */
    202: KnowledgeDocument;
};

export type KnowledgeDocumentIngestResponse = KnowledgeDocumentIngestResponses[keyof KnowledgeDocumentIngestResponses];

export type KnowledgeDocumentReindexData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}/reindex';
};

export type KnowledgeDocumentReindexErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentReindexError = KnowledgeDocumentReindexErrors[keyof KnowledgeDocumentReindexErrors];

export type KnowledgeDocumentReindexResponses = {
    /**
     * Successful Response
     */
    202: KnowledgeDocument;
};

export type KnowledgeDocumentReindexResponse = KnowledgeDocumentReindexResponses[keyof KnowledgeDocumentReindexResponses];

export type KnowledgeDocumentCancelIngestionData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}/documents/{document_id}/cancel';
};

export type KnowledgeDocumentCancelIngestionErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeDocumentCancelIngestionError = KnowledgeDocumentCancelIngestionErrors[keyof KnowledgeDocumentCancelIngestionErrors];

export type KnowledgeDocumentCancelIngestionResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocument;
};

export type KnowledgeDocumentCancelIngestionResponse = KnowledgeDocumentCancelIngestionResponses[keyof KnowledgeDocumentCancelIngestionResponses];

export type KnowledgeBaseDeleteData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}';
};

export type KnowledgeBaseDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeBaseDeleteError = KnowledgeBaseDeleteErrors[keyof KnowledgeBaseDeleteErrors];

export type KnowledgeBaseDeleteResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBase;
};

export type KnowledgeBaseDeleteResponse = KnowledgeBaseDeleteResponses[keyof KnowledgeBaseDeleteResponses];

export type KnowledgeBaseGetOneData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}';
};

export type KnowledgeBaseGetOneErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeBaseGetOneError = KnowledgeBaseGetOneErrors[keyof KnowledgeBaseGetOneErrors];

export type KnowledgeBaseGetOneResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBase;
};

export type KnowledgeBaseGetOneResponse = KnowledgeBaseGetOneResponses[keyof KnowledgeBaseGetOneResponses];

export type KnowledgeBaseUpdateData = {
    body: KnowledgeBaseUpdate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/knowledge-bases/{knowledge_base_id}';
};

export type KnowledgeBaseUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Conflict
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type KnowledgeBaseUpdateError = KnowledgeBaseUpdateErrors[keyof KnowledgeBaseUpdateErrors];

export type KnowledgeBaseUpdateResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBase;
};

export type KnowledgeBaseUpdateResponse = KnowledgeBaseUpdateResponses[keyof KnowledgeBaseUpdateResponses];

export type UserSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/user';
};

export type UserSettingsGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type UserSettingsGetError = UserSettingsGetErrors[keyof UserSettingsGetErrors];

export type UserSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UserSettingsGetResponse = UserSettingsGetResponses[keyof UserSettingsGetResponses];

export type UserSettingsBulkUpdateData = {
    /**
     * Updates
     */
    body: {
        [key: string]: JsonValue;
    };
    path?: never;
    query?: never;
    url: '/settings/user';
};

export type UserSettingsBulkUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingsBulkUpdateError = UserSettingsBulkUpdateErrors[keyof UserSettingsBulkUpdateErrors];

export type UserSettingsBulkUpdateResponses = {
    /**
     * Successful Response
     */
    200: UserSettings;
};

export type UserSettingsBulkUpdateResponse = UserSettingsBulkUpdateResponses[keyof UserSettingsBulkUpdateResponses];

export type UserSettingDeleteData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/user/{key}';
};

export type UserSettingDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingDeleteError = UserSettingDeleteErrors[keyof UserSettingDeleteErrors];

export type UserSettingDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UserSettingUpdateData = {
    body: UpdateSettingValue;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/user/{key}';
};

export type UserSettingUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserSettingUpdateError = UserSettingUpdateErrors[keyof UserSettingUpdateErrors];

export type UserSettingUpdateResponses = {
    /**
     * Successful Response
     */
    200: Setting;
};

export type UserSettingUpdateResponse = UserSettingUpdateResponses[keyof UserSettingUpdateResponses];

export type AppProviderModelsDiscoverData = {
    body: ProviderDiscoveryRequestWritable;
    path?: never;
    query?: never;
    url: '/settings/app/providers/discover';
};

export type AppProviderModelsDiscoverErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
    /**
     * Provider discovery failed
     */
    502: ErrorDetail;
    /**
     * Provider discovery timed out
     */
    504: ErrorDetail;
};

export type AppProviderModelsDiscoverError = AppProviderModelsDiscoverErrors[keyof AppProviderModelsDiscoverErrors];

export type AppProviderModelsDiscoverResponses = {
    /**
     * Successful Response
     */
    200: ProviderDiscoveryResponse;
};

export type AppProviderModelsDiscoverResponse = AppProviderModelsDiscoverResponses[keyof AppProviderModelsDiscoverResponses];

export type AppSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/app';
};

export type AppSettingsGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AppSettingsGetError = AppSettingsGetErrors[keyof AppSettingsGetErrors];

export type AppSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: ApplicationSettings;
};

export type AppSettingsGetResponse = AppSettingsGetResponses[keyof AppSettingsGetResponses];

export type AppSettingsBulkUpdateData = {
    body: BulkUpdateSettingRequest;
    path?: never;
    query?: never;
    url: '/settings/app';
};

export type AppSettingsBulkUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingsBulkUpdateError = AppSettingsBulkUpdateErrors[keyof AppSettingsBulkUpdateErrors];

export type AppSettingsBulkUpdateResponses = {
    /**
     * Successful Response
     */
    200: ApplicationSettings;
};

export type AppSettingsBulkUpdateResponse = AppSettingsBulkUpdateResponses[keyof AppSettingsBulkUpdateResponses];

export type AppSettingDeleteData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/app/{key}';
};

export type AppSettingDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingDeleteError = AppSettingDeleteErrors[keyof AppSettingDeleteErrors];

export type AppSettingDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AppSettingUpdateData = {
    body: UpdateSettingValue;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/app/{key}';
};

export type AppSettingUpdateErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppSettingUpdateError = AppSettingUpdateErrors[keyof AppSettingUpdateErrors];

export type AppSettingUpdateResponses = {
    /**
     * Successful Response
     */
    200: Setting;
};

export type AppSettingUpdateResponse = AppSettingUpdateResponses[keyof AppSettingUpdateResponses];

export type AppCaptioningGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/app/captioning';
};

export type AppCaptioningGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AppCaptioningGetError = AppCaptioningGetErrors[keyof AppCaptioningGetErrors];

export type AppCaptioningGetResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeCaptionConfiguration;
};

export type AppCaptioningGetResponse = AppCaptioningGetResponses[keyof AppCaptioningGetResponses];

export type AppCaptioningUpdateData = {
    body: KnowledgeCaptionConfigurationUpdate;
    path?: never;
    query?: never;
    url: '/settings/app/captioning';
};

export type AppCaptioningUpdateErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AppCaptioningUpdateError = AppCaptioningUpdateErrors[keyof AppCaptioningUpdateErrors];

export type AppCaptioningUpdateResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeCaptionConfiguration;
};

export type AppCaptioningUpdateResponse = AppCaptioningUpdateResponses[keyof AppCaptioningUpdateResponses];

export type AppCaptionModelStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/app/caption-model/status';
};

export type AppCaptionModelStatusErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AppCaptionModelStatusError = AppCaptionModelStatusErrors[keyof AppCaptionModelStatusErrors];

export type AppCaptionModelStatusResponses = {
    /**
     * Successful Response
     */
    200: CaptionModelStatus;
};

export type AppCaptionModelStatusResponse = AppCaptionModelStatusResponses[keyof AppCaptionModelStatusResponses];

export type AppCaptionModelDownloadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/app/caption-model/download';
};

export type AppCaptionModelDownloadErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Download already in progress
     */
    409: ErrorDetail;
};

export type AppCaptionModelDownloadError = AppCaptionModelDownloadErrors[keyof AppCaptionModelDownloadErrors];

export type AppCaptionModelDownloadResponses = {
    /**
     * Successful Response
     */
    202: CaptionModelStatus;
};

export type AppCaptionModelDownloadResponse = AppCaptionModelDownloadResponses[keyof AppCaptionModelDownloadResponses];

export type AppCaptionModelCancelData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/app/caption-model/cancel';
};

export type AppCaptionModelCancelErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AppCaptionModelCancelError = AppCaptionModelCancelErrors[keyof AppCaptionModelCancelErrors];

export type AppCaptionModelCancelResponses = {
    /**
     * Successful Response
     */
    200: CaptionModelStatus;
};

export type AppCaptionModelCancelResponse = AppCaptionModelCancelResponses[keyof AppCaptionModelCancelResponses];

export type UserCreateUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users/';
};

export type UserCreateUserErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserCreateUserError = UserCreateUserErrors[keyof UserCreateUserErrors];

export type UserCreateUserResponses = {
    /**
     * Response Usercreateuser
     *
     * Successful Response
     */
    200: boolean;
};

export type UserCreateUserResponse = UserCreateUserResponses[keyof UserCreateUserResponses];

export type UserDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UserDeleteErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type UserDeleteError = UserDeleteErrors[keyof UserDeleteErrors];

export type UserDeleteResponses = {
    /**
     * Response Userdelete
     *
     * Successful Response
     */
    200: boolean;
};

export type UserDeleteResponse = UserDeleteResponses[keyof UserDeleteResponses];

export type ToolsGetActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tools/active';
};

export type ToolsGetActiveErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type ToolsGetActiveError = ToolsGetActiveErrors[keyof ToolsGetActiveErrors];

export type ToolsGetActiveResponses = {
    /**
     * Successful Response
     */
    200: ToolInfoList;
};

export type ToolsGetActiveResponse = ToolsGetActiveResponses[keyof ToolsGetActiveResponses];

export type ToolsGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tools/all';
};

export type ToolsGetAllErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type ToolsGetAllError = ToolsGetAllErrors[keyof ToolsGetAllErrors];

export type ToolsGetAllResponses = {
    /**
     * Successful Response
     */
    200: ToolInfoList;
};

export type ToolsGetAllResponse = ToolsGetAllResponses[keyof ToolsGetAllResponses];

export type ComponentsByTypeData = {
    body?: never;
    path: {
        component_type: ComponentType;
    };
    query?: never;
    url: '/components/by_type/{component_type}';
};

export type ComponentsByTypeErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type ComponentsByTypeError = ComponentsByTypeErrors[keyof ComponentsByTypeErrors];

export type ComponentsByTypeResponses = {
    /**
     * Successful Response
     */
    200: ComponentListResponse;
};

export type ComponentsByTypeResponse = ComponentsByTypeResponses[keyof ComponentsByTypeResponses];

export type AgentsGetUserAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents';
};

export type AgentsGetUserAgentsErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AgentsGetUserAgentsError = AgentsGetUserAgentsErrors[keyof AgentsGetUserAgentsErrors];

export type AgentsGetUserAgentsResponses = {
    /**
     * Successful Response
     */
    200: UserAgents;
};

export type AgentsGetUserAgentsResponse = AgentsGetUserAgentsResponses[keyof AgentsGetUserAgentsResponses];

export type AgentsUpsertAgentProfileData = {
    body: PartialAgentProfile;
    path?: never;
    query?: never;
    url: '/agents';
};

export type AgentsUpsertAgentProfileErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AgentsUpsertAgentProfileError = AgentsUpsertAgentProfileErrors[keyof AgentsUpsertAgentProfileErrors];

export type AgentsUpsertAgentProfileResponses = {
    /**
     * Successful Response
     */
    200: AgentProfile;
};

export type AgentsUpsertAgentProfileResponse = AgentsUpsertAgentProfileResponses[keyof AgentsUpsertAgentProfileResponses];

export type AgentKnowledgeBaseAssignmentsGetData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/knowledge-bases';
};

export type AgentKnowledgeBaseAssignmentsGetErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AgentKnowledgeBaseAssignmentsGetError = AgentKnowledgeBaseAssignmentsGetErrors[keyof AgentKnowledgeBaseAssignmentsGetErrors];

export type AgentKnowledgeBaseAssignmentsGetResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBaseAssignmentList;
};

export type AgentKnowledgeBaseAssignmentsGetResponse = AgentKnowledgeBaseAssignmentsGetResponses[keyof AgentKnowledgeBaseAssignmentsGetResponses];

export type AgentKnowledgeBaseAssignmentsReplaceData = {
    body: KnowledgeBaseAssignmentReplace;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/knowledge-bases';
};

export type AgentKnowledgeBaseAssignmentsReplaceErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AgentKnowledgeBaseAssignmentsReplaceError = AgentKnowledgeBaseAssignmentsReplaceErrors[keyof AgentKnowledgeBaseAssignmentsReplaceErrors];

export type AgentKnowledgeBaseAssignmentsReplaceResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBaseAssignmentList;
};

export type AgentKnowledgeBaseAssignmentsReplaceResponse = AgentKnowledgeBaseAssignmentsReplaceResponses[keyof AgentKnowledgeBaseAssignmentsReplaceResponses];

export type AgentsDeleteAgentData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}';
};

export type AgentsDeleteAgentErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AgentsDeleteAgentError = AgentsDeleteAgentErrors[keyof AgentsDeleteAgentErrors];

export type AgentsDeleteAgentResponses = {
    /**
     * Successful Response
     */
    200: AgentProfile;
};

export type AgentsDeleteAgentResponse = AgentsDeleteAgentResponses[keyof AgentsDeleteAgentResponses];

export type AgentsGetSubAgentTracesData = {
    body?: never;
    path: {
        /**
         * Parent Message Id
         */
        parent_message_id: string;
    };
    query?: never;
    url: '/agents/traces/{parent_message_id}';
};

export type AgentsGetSubAgentTracesErrors = {
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: ErrorDetail;
};

export type AgentsGetSubAgentTracesError = AgentsGetSubAgentTracesErrors[keyof AgentsGetSubAgentTracesErrors];

export type AgentsGetSubAgentTracesResponses = {
    /**
     * Response Agentsgetsubagenttraces
     *
     * Successful Response
     */
    200: Array<SubAgentTrace>;
};

export type AgentsGetSubAgentTracesResponse = AgentsGetSubAgentTracesResponses[keyof AgentsGetSubAgentTracesResponses];
