// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ChatInfo
 */
export const zChatInfo = z.object({
    id: z.uuid(),
    user_id: z.string(),
    created_at: z.iso.datetime({ local: true }),
    updated_at: z.iso.datetime({ local: true }),
    title: z.string().nullish(),
    folder_id: z.string().nullish()
});

/**
 * ChatModelList
 */
export const zChatModelList = z.object({
    chats: z.array(zChatInfo)
});

/**
 * ChatUpdateRequest
 */
export const zChatUpdateRequest = z.object({
    title: z.unknown().optional(),
    folder_id: z.unknown().optional()
});

/**
 * CreateUserRequest
 */
export const zCreateUserRequest = z.object({
    user_id: z.string(),
    system_key: z.string().nullish()
});

/**
 * ErrorDetail
 */
export const zErrorDetail = z.object({
    detail: z.string(),
    code: z.int()
});

/**
 * FolderModel
 */
export const zFolderModel = z.object({
    id: z.uuid(),
    user_id: z.string(),
    title: z.string(),
    created_at: z.iso.datetime({ local: true }),
    updated_at: z.iso.datetime({ local: true }),
    parent_id: z.union([
        z.uuid(),
        z.unknown()
    ]),
    sessions: z.array(zChatInfo).optional(),
    children: z.array(z.lazy((): any => zFolderModel)).optional()
});

/**
 * FolderModelList
 */
export const zFolderModelList = z.object({
    folders: z.array(zFolderModel)
});

/**
 * Function
 */
export const zFunction = z.object({
    name: z.string(),
    arguments: z.string()
});

export const zJsonValue = z.unknown();

/**
 * LLMProvider
 */
export const zLlmProvider = z.object({
    name: z.string(),
    base_url: z.string(),
    api_key: z.string(),
    models: z.array(z.string())
});

/**
 * ApplicationSettings
 */
export const zApplicationSettings = z.object({
    llm_providers: z.array(zLlmProvider).optional()
});

/**
 * MessageStatus
 */
export const zMessageStatus = z.enum(['pending', 'completed']);

/**
 * NewChatRequest
 */
export const zNewChatRequest = z.object({
    user_prompt: z.string(),
    folder_id: z.unknown().optional()
});

/**
 * NewFolderRequest
 */
export const zNewFolderRequest = z.object({
    title: z.string(),
    parent_id: z.string().nullable()
});

/**
 * Setting
 */
export const zSetting = z.object({
    key: z.string(),
    value: zJsonValue
});

/**
 * ToolCall
 */
export const zToolCall = z.object({
    id: z.string(),
    function: zFunction,
    type: z.string().optional().default('function')
});

/**
 * MessageModel
 */
export const zMessageModel = z.object({
    role: z.string(),
    content: z.string(),
    token_count: z.int(),
    thinking: z.string().nullish(),
    tool_calls: z.array(zToolCall).nullish(),
    tool_call_id: z.string().nullish(),
    id: z.uuid(),
    status: zMessageStatus,
    created_at: z.int(),
    active_child_id: z.string().nullable(),
    has_siblings: z.boolean().optional().default(false),
    sibling_count: z.int().optional().default(0),
    current_sibling_index: z.int().optional().default(-1)
});

/**
 * ChatModel
 */
export const zChatModel = z.object({
    info: zChatInfo,
    messages: z.array(zMessageModel)
});

/**
 * UpdateSettingValue
 */
export const zUpdateSettingValue = z.object({
    value: zJsonValue
});

/**
 * UserSettings
 */
export const zUserSettings = z.object({
    theme: z.string().optional().default('light'),
    font_size: z.string().optional().default('16px')
});

export const zGetFilePath = z.object({
    filename: z.string()
});

/**
 * Returns the user's file
 */
export const zGetFileResponse = z.string();

/**
 * Successful Response
 */
export const zChatSessionGetManyResponse = zChatModelList;

export const zChatSessionCreateBody = zNewChatRequest;

/**
 * Successful Response
 */
export const zChatSessionCreateResponse = zChatModel;

export const zChatSessionGetOnePath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionGetOneResponse = zChatModel;

export const zChatSessionDeletePath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionDeleteResponse = zChatModel;

export const zChatSessionUpdateBody = zChatUpdateRequest;

export const zChatSessionUpdatePath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionUpdateResponse = zChatModel;

/**
 * Successful Response
 */
export const zFolderGetManyResponse = zFolderModelList;

export const zFolderCreateBody = zNewFolderRequest;

/**
 * Successful Response
 */
export const zFolderCreateResponse = zFolderModel;

export const zFolderDeletePath = z.object({
    folder_id: z.string()
});

/**
 * Successful Response
 */
export const zFolderDeleteResponse = zFolderModel;

export const zFolderGetOnePath = z.object({
    folder_id: z.uuid()
});

/**
 * Successful Response
 */
export const zFolderGetOneResponse = zFolderModel;

/**
 * Successful Response
 */
export const zUserSettingsGetResponse = zUserSettings;

/**
 * Updates
 */
export const zUserSettingsBulkUpdateBody = z.record(z.string(), zJsonValue);

/**
 * Successful Response
 */
export const zUserSettingsBulkUpdateResponse = zUserSettings;

export const zUserSettingDeletePath = z.object({
    key: z.string()
});

export const zUserSettingUpdateBody = zUpdateSettingValue;

export const zUserSettingUpdatePath = z.object({
    key: z.string()
});

/**
 * Successful Response
 */
export const zUserSettingUpdateResponse = zSetting;

/**
 * Successful Response
 */
export const zAppSettingsGetResponse = zApplicationSettings;

/**
 * Updates
 */
export const zAppSettingsBulkUpdateBody = z.record(z.string(), zJsonValue);

/**
 * Successful Response
 */
export const zAppSettingsBulkUpdateResponse = zApplicationSettings;

export const zAppSettingDeletePath = z.object({
    key: z.string()
});

export const zAppSettingUpdateBody = zUpdateSettingValue;

export const zAppSettingUpdatePath = z.object({
    key: z.string()
});

/**
 * Successful Response
 */
export const zAppSettingUpdateResponse = zSetting;

export const zUserCreateUserBody = zCreateUserRequest;

/**
 * Response Usercreateuser
 *
 * Successful Response
 */
export const zUserCreateUserResponse = z.boolean();

export const zUserSettingDelete2Path = z.object({
    user_id: z.string()
});
