// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ChatSessionInfo
 */
export const zChatSessionInfo = z.object({
    id: z.uuid(),
    user_id: z.string(),
    title: z.string(),
    folder_id: z.union([
        z.uuid(),
        z.unknown()
    ]),
    system_prompt: z.union([
        z.string(),
        z.unknown()
    ]),
    created_at: z.iso.datetime({ local: true }),
    updated_at: z.iso.datetime({ local: true })
});

/**
 * ChatSessionInfoList
 */
export const zChatSessionInfoList = z.object({
    sessions: z.array(zChatSessionInfo)
});

/**
 * ChatSessionUpdate
 */
export const zChatSessionUpdate = z.object({
    title: z.unknown().optional(),
    folder_id: z.unknown().optional()
});

/**
 * ErrorDetail
 */
export const zErrorDetail = z.object({
    detail: z.string(),
    code: z.int()
});

/**
 * FolderModel
 */
export const zFolderModel = z.object({
    id: z.uuid(),
    user_id: z.string(),
    title: z.string(),
    created_at: z.iso.datetime({ local: true }),
    updated_at: z.iso.datetime({ local: true }),
    parent_id: z.union([
        z.uuid(),
        z.unknown()
    ]),
    sessions: z.array(zChatSessionInfo).optional(),
    children: z.array(z.lazy((): any => zFolderModel)).optional()
});

/**
 * FolderModelList
 */
export const zFolderModelList = z.object({
    folders: z.array(zFolderModel)
});

/**
 * MessageModel
 */
export const zMessageModel = z.object({
    id: z.uuid(),
    role: z.string(),
    content: z.string(),
    thinking: z.string(),
    created_at: z.int(),
    active_child_id: z.string().nullable(),
    has_siblings: z.boolean().optional().default(false),
    sibling_count: z.int().optional().default(0),
    current_sibling_index: z.int().optional().default(-1)
});

/**
 * ChatSessionModel
 */
export const zChatSessionModel = z.object({
    info: zChatSessionInfo,
    messages: z.array(zMessageModel)
});

/**
 * NewChatSessionRequest
 */
export const zNewChatSessionRequest = z.object({
    folder_id: z.string().nullable()
});

/**
 * NewFolderRequest
 */
export const zNewFolderRequest = z.object({
    title: z.string(),
    parent_id: z.string().nullable()
});

export const zGetFilePath = z.object({
    filename: z.string()
});

/**
 * Returns the user's file
 */
export const zGetFileResponse = z.string();

/**
 * Successful Response
 */
export const zChatSessionGetManyResponse = zChatSessionInfoList;

export const zChatSessionCreateBody = zNewChatSessionRequest;

/**
 * Successful Response
 */
export const zChatSessionCreateResponse = zChatSessionModel;

export const zChatSessionGetOnePath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionGetOneResponse = zChatSessionModel;

export const zChatSessionDeletePath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionDeleteResponse = zChatSessionModel;

export const zChatSessionUpdateBody = zChatSessionUpdate;

export const zChatSessionUpdatePath = z.object({
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionUpdateResponse = zChatSessionModel;

/**
 * Successful Response
 */
export const zFolderGetManyResponse = zFolderModelList;

export const zFolderCreateBody = zNewFolderRequest;

/**
 * Successful Response
 */
export const zFolderCreateResponse = zFolderModel;

export const zFolderDeletePath = z.object({
    folder_id: z.string()
});

/**
 * Successful Response
 */
export const zFolderDeleteResponse = zFolderModel;

export const zFolderGetOnePath = z.object({
    folder_id: z.uuid()
});

/**
 * Successful Response
 */
export const zFolderGetOneResponse = zFolderModel;
