// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Body_fileUpload
 */
export const zBodyFileUpload = z.object({
    files: z.array(z.string())
});

/**
 * BulkDeleteChatRequest
 */
export const zBulkDeleteChatRequest = z.object({
    chat_ids: z.array(z.uuid()).min(1).max(100)
});

/**
 * BulkDeleteChatResponse
 */
export const zBulkDeleteChatResponse = z.object({
    deleted_chat_ids: z.array(z.uuid())
});

/**
 * ChatCompletionParams
 */
export const zChatCompletionParams = z.object({
    reasoning_effort: z.unknown().optional(),
    temperature: z.number().optional(),
    top_p: z.number().optional(),
    frequency_penalty: z.number().optional(),
    presence_penalty: z.number().optional(),
    seed: z.int().optional(),
    stop: z.union([
        z.string(),
        z.array(z.string())
    ]).optional(),
    extra_body: z.record(z.string(), z.unknown()).optional(),
    tool_choice: z.union([
        z.enum([
            'required',
            'auto',
            'none'
        ]),
        z.record(z.string(), z.unknown())
    ]).optional(),
    max_tokens: z.int().optional(),
    modalities: z.array(z.enum(['text', 'audio'])).optional(),
    audio: z.record(z.string(), z.unknown()).optional(),
    prediction: z.record(z.string(), z.unknown()).optional(),
    parallel_tool_calls: z.boolean().optional(),
    n: z.int().optional(),
    logit_bias: z.record(z.string(), z.int()).optional(),
    logprobs: z.boolean().optional(),
    top_logprobs: z.int().optional(),
    extra_headers: z.record(z.string(), z.string()).optional(),
    extra_query: z.record(z.string(), z.unknown()).optional(),
    timeout: z.number().nullish()
});

/**
 * AgentProfile
 */
export const zAgentProfile = z.object({
    name: z.string(),
    description: z.string(),
    sub_agent: z.boolean(),
    model_id: z.uuid().nullable(),
    system_prompt: z.string().nullable(),
    max_steps: z.int(),
    chat_parameters: zChatCompletionParams.optional(),
    tools: z.array(z.string()).nullish(),
    id: z.uuid().optional().default('b1f6380a-62ed-487c-ba6c-05ae33383ab6')
});

/**
 * ChatInfo
 */
export const zChatInfo = z.object({
    id: z.uuid(),
    user_id: z.string(),
    created_at: z.int(),
    updated_at: z.int(),
    allowed_tools: z.array(z.string()).optional(),
    title: z.string().nullish(),
    folder_id: z.uuid().nullish(),
    agent_id: z.uuid().nullish(),
    preview: z.string().nullish(),
    message_count: z.int().nullish()
});

/**
 * ChatInfoList
 */
export const zChatInfoList = z.object({
    chats: z.array(zChatInfo)
});

/**
 * ChatUpdateRequest
 */
export const zChatUpdateRequest = z.object({
    title: z.string().nullish(),
    folder_id: z.uuid().nullish()
});

/**
 * ComponentProviderParameters
 */
export const zComponentProviderParameters = z.object({
    name: z.string(),
    parameters: z.record(z.string(), z.string()).optional()
});

/**
 * ComponentResponse
 */
export const zComponentResponse = z.object({
    type: z.string(),
    name: z.string(),
    parameters: z.record(z.string(), z.unknown())
});

/**
 * ComponentListResponse
 */
export const zComponentListResponse = z.object({
    items: z.array(zComponentResponse)
});

/**
 * ComponentType
 */
export const zComponentType = z.enum([
    'WebSearch',
    'ImageSearch',
    'ImageGenerator'
]);

/**
 * CreateUserRequest
 */
export const zCreateUserRequest = z.object({
    user_id: z.string(),
    system_key: z.string().nullish()
});

/**
 * ErrorDetail
 */
export const zErrorDetail = z.object({
    detail: z.string(),
    code: z.int()
});

/**
 * FileContentStatus
 */
export const zFileContentStatus = z.enum([
    'pending',
    'ready',
    'unsupported',
    'failed'
]);

/**
 * FileKind
 */
export const zFileKind = z.enum([
    'image',
    'text',
    'document',
    'other'
]);

/**
 * Folder
 */
export const zFolder = z.object({
    id: z.uuid(),
    user_id: z.string(),
    title: z.string(),
    created_at: z.int(),
    updated_at: z.int(),
    parent_id: z.uuid().nullable(),
    sessions: z.array(zChatInfo).optional(),
    children: z.array(z.lazy((): any => zFolder)).optional()
});

/**
 * FolderChatList
 */
export const zFolderChatList = z.object({
    chats: z.array(zChatInfo),
    total: z.int().gte(0),
    page: z.int().gte(1),
    page_size: z.int().gte(1)
});

/**
 * FolderList
 */
export const zFolderList = z.object({
    folders: z.array(zFolder)
});

/**
 * Function
 */
export const zFunction = z.object({
    name: z.string(),
    arguments: z.string()
});

export const zJsonValue = z.unknown();

/**
 * BulkUpdateSettingRequest
 */
export const zBulkUpdateSettingRequest = z.object({
    values: z.record(z.string(), zJsonValue)
});

/**
 * MessageFileReference
 */
export const zMessageFileReference = z.object({
    filename: z.string(),
    name: z.string(),
    mime_type: z.string(),
    size: z.int().gte(0),
    kind: zFileKind,
    status: zFileContentStatus
});

/**
 * MessageStatus
 */
export const zMessageStatus = z.enum([
    'pending',
    'completed',
    'cancelled'
]);

/**
 * ModelCapabilitySource
 */
export const zModelCapabilitySource = z.enum([
    'catalog',
    'provider',
    'manual',
    'unknown'
]);

/**
 * Llm
 */
export const zLlm = z.object({
    id: z.uuid(),
    name: z.string(),
    provider_id: z.uuid(),
    is_active: z.boolean(),
    context_window: z.int().gt(0).nullish(),
    supports_vision: z.boolean().nullish(),
    context_window_source: zModelCapabilitySource.optional().default('unknown'),
    vision_source: zModelCapabilitySource.optional().default('unknown')
});

/**
 * LlmDisplayInfo
 */
export const zLlmDisplayInfo = z.object({
    id: z.uuid(),
    name: z.string(),
    provider_id: z.uuid(),
    provider_name: z.string(),
    context_window: z.int().gt(0).nullish(),
    supports_vision: z.boolean().nullish(),
    context_window_source: zModelCapabilitySource.optional().default('unknown'),
    vision_source: zModelCapabilitySource.optional().default('unknown')
});

/**
 * NewChatRequest
 */
export const zNewChatRequest = z.object({
    user_prompt: z.string(),
    agent_id: z.uuid().nullish(),
    folder_id: z.uuid().nullish(),
    files: z.array(z.string()).optional()
});

/**
 * NewFolderRequest
 */
export const zNewFolderRequest = z.object({
    title: z.string(),
    parent_id: z.uuid().nullish()
});

/**
 * PartialAgentProfile
 */
export const zPartialAgentProfile = z.object({
    name: z.string(),
    description: z.string(),
    sub_agent: z.boolean(),
    model_id: z.uuid().nullable(),
    system_prompt: z.string().nullable(),
    max_steps: z.int(),
    chat_parameters: zChatCompletionParams.optional(),
    tools: z.array(z.string()).nullish(),
    id: z.uuid().nullish()
});

/**
 * ProviderDiscoveryResponse
 */
export const zProviderDiscoveryResponse = z.object({
    models: z.array(zLlm),
    catalog_version: z.string().nullish(),
    warnings: z.array(z.string()).optional()
});

/**
 * ProviderType
 */
export const zProviderType = z.enum(['openai', 'generic_openai']);

/**
 * Provider
 */
export const zProvider = z.object({
    name: z.string(),
    base_url: z.string(),
    api_key: z.string(),
    id: z.uuid(),
    provider_type: zProviderType.optional().default('generic_openai'),
    models: z.array(zLlm)
});

/**
 * ApplicationSettings
 */
export const zApplicationSettings = z.object({
    llm_providers: z.array(zProvider).optional(),
    draft_model_id: z.uuid().nullish(),
    web_search_provider: zComponentProviderParameters.nullish(),
    image_search_provider: zComponentProviderParameters.nullish(),
    active_tools: z.array(z.string())
});

/**
 * ProviderDiscoveryRequest
 */
export const zProviderDiscoveryRequest = z.object({
    provider_type: zProviderType,
    base_url: z.string().optional().default(''),
    provider_id: z.uuid(),
    existing_models: z.array(zLlm).optional(),
    draft_model_id: z.uuid().nullish()
});

/**
 * SearchMatchSource
 */
export const zSearchMatchSource = z.enum([
    'title',
    'content',
    'folder_title'
]);

/**
 * SearchResultKind
 */
export const zSearchResultKind = z.enum(['chat', 'folder']);

/**
 * SearchResult
 */
export const zSearchResult = z.object({
    kind: zSearchResultKind,
    id: z.uuid(),
    title: z.string(),
    updated_at: z.int(),
    folder_id: z.uuid().nullish(),
    match_source: zSearchMatchSource,
    snippet: z.string().nullish(),
    path: z.array(z.string()).optional()
});

/**
 * SearchResultList
 */
export const zSearchResultList = z.object({
    results: z.array(zSearchResult),
    total: z.int().gte(0),
    page: z.int().gte(1),
    page_size: z.int().gte(1)
});

/**
 * Setting
 */
export const zSetting = z.object({
    key: z.string(),
    value: zJsonValue
});

/**
 * SubAgentTrace
 */
export const zSubAgentTrace = z.object({
    id: z.uuid(),
    created_at: z.int(),
    user_id: z.string(),
    parent_message_id: z.uuid().nullish(),
    sub_agent_id: z.uuid(),
    sub_agent_name: z.string(),
    prompt: z.string(),
    caller_context: z.string().nullish(),
    messages: z.array(z.record(z.string(), z.unknown())).optional(),
    result: z.string().nullish(),
    step_count: z.int().optional().default(0),
    total_tokens: z.int().optional().default(0),
    elapsed_ms: z.int().optional().default(0),
    depth: z.int().optional().default(0)
});

/**
 * ToolCall
 */
export const zToolCall = z.object({
    id: z.string(),
    function: zFunction,
    type: z.literal('function').optional().default('function')
});

/**
 * ToolInfo
 */
export const zToolInfo = z.object({
    name: z.string(),
    description: z.string(),
    component_type: zComponentType.nullish()
});

/**
 * ToolInfoList
 */
export const zToolInfoList = z.object({
    items: z.array(zToolInfo)
});

/**
 * ToolResult
 */
export const zToolResult = z.object({
    content: z.string(),
    raw_result: z.unknown(),
    is_empty: z.boolean(),
    tool_call: zToolCall
});

/**
 * Message
 */
export const zMessage = z.object({
    role: z.string(),
    content: z.string(),
    token_count: z.int(),
    thinking: z.string().nullish(),
    tool_calls: z.array(zToolCall).nullish(),
    id: z.uuid(),
    status: zMessageStatus,
    created_at: z.int(),
    model_id: z.uuid().nullish(),
    tool_call_results: z.array(zToolResult).nullish(),
    files: z.array(zMessageFileReference).optional(),
    active_child_id: z.uuid().nullish(),
    has_siblings: z.boolean().optional().default(false),
    sibling_count: z.int().optional().default(0),
    current_sibling_index: z.int().optional().default(-1),
    parent_message_id: z.uuid().nullish(),
    next_sibling_id: z.uuid().nullish(),
    previous_sibling_id: z.uuid().nullish()
});

/**
 * Chat
 */
export const zChat = z.object({
    info: zChatInfo,
    messages: z.array(zMessage)
});

/**
 * UpdateMessageRequest
 */
export const zUpdateMessageRequest = z.object({
    content: z.string().nullish(),
    thinking: z.string().nullish(),
    active_child_id: z.uuid().nullish(),
    status: zMessageStatus.nullish(),
    tool_results: z.array(zToolResult).nullish()
});

/**
 * UpdateSettingValue
 */
export const zUpdateSettingValue = z.object({
    value: zJsonValue
});

/**
 * UserAgents
 */
export const zUserAgents = z.object({
    agents: z.record(z.string(), zAgentProfile)
});

/**
 * UserFile
 */
export const zUserFile = z.object({
    id: z.uuid(),
    filename: z.string(),
    original_name: z.string(),
    size: z.int().gte(0),
    mime_type: z.string(),
    kind: zFileKind,
    content_status: zFileContentStatus,
    content_error: z.string().nullable(),
    created_at: z.int(),
    updated_at: z.int()
});

/**
 * UserFileList
 */
export const zUserFileList = z.object({
    files: z.array(zUserFile),
    total: z.int().gte(0).optional().default(0),
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).optional().default(50)
});

/**
 * UserSettings
 */
export const zUserSettings = z.object({
    theme: z.string().optional().default('light'),
    font_size: z.string().optional().default('16px'),
    models: z.array(zLlmDisplayInfo).optional(),
    default_model_id: z.uuid().nullish(),
    agents: z.record(z.string(), zAgentProfile).optional(),
    default_agent_id: z.uuid().nullish()
});

/**
 * ProviderDiscoveryRequest
 */
export const zProviderDiscoveryRequestWritable = z.object({
    provider_type: zProviderType,
    base_url: z.string().optional().default(''),
    api_key: z.string().min(1),
    provider_id: z.uuid(),
    existing_models: z.array(zLlm).optional(),
    draft_model_id: z.uuid().nullish()
});

export const zFileGetManyQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(50)
});

/**
 * Successful Response
 */
export const zFileGetManyResponse = zUserFileList;

export const zFileUploadBody = zBodyFileUpload;

/**
 * Successful Response
 */
export const zFileUploadResponse = zUserFileList;

export const zFileDeletePath = z.object({
    filename: z.string()
});

/**
 * Successful Response
 */
export const zFileDeleteResponse = zUserFile;

export const zGetFilePath = z.object({
    filename: z.string()
});

/**
 * Returns the user's file
 */
export const zGetFileResponse = z.string();

/**
 * Successful Response
 */
export const zChatSessionGetManyResponse = zChatInfoList;

export const zChatSessionCreateBody = zNewChatRequest;

/**
 * Successful Response
 */
export const zChatSessionCreateResponse = zChat;

export const zChatSessionBulkDeleteBody = zBulkDeleteChatRequest;

/**
 * Successful Response
 */
export const zChatSessionBulkDeleteResponse = zBulkDeleteChatResponse;

export const zChatSessionDeletePath = z.object({
    chat_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionDeleteResponse = zChat;

export const zChatSessionGetOnePath = z.object({
    chat_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionGetOneResponse = zChat;

export const zChatSessionUpdateBody = zChatUpdateRequest;

export const zChatSessionUpdatePath = z.object({
    chat_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChatSessionUpdateResponse = zChat;

export const zChatSearchQuery = z.object({
    q: z.string(),
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * Successful Response
 */
export const zChatSearchResponse = zSearchResultList;

export const zMessageUpdateBody = zUpdateMessageRequest;

export const zMessageUpdatePath = z.object({
    chat_id: z.uuid(),
    message_id: z.uuid()
});

/**
 * Successful Response
 */
export const zMessageUpdateResponse = zMessage;

/**
 * Successful Response
 */
export const zFolderGetManyResponse = zFolderList;

export const zFolderCreateBody = zNewFolderRequest;

/**
 * Successful Response
 */
export const zFolderCreateResponse = zFolder;

export const zFolderChatGetManyPath = z.object({
    folder_id: z.uuid()
});

export const zFolderChatGetManyQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * Successful Response
 */
export const zFolderChatGetManyResponse = zFolderChatList;

export const zFolderDeletePath = z.object({
    folder_id: z.string()
});

/**
 * Successful Response
 */
export const zFolderDeleteResponse = zFolder;

export const zFolderGetOnePath = z.object({
    folder_id: z.uuid()
});

/**
 * Successful Response
 */
export const zFolderGetOneResponse = zFolder;

/**
 * Successful Response
 */
export const zUserSettingsGetResponse = zUserSettings;

/**
 * Updates
 */
export const zUserSettingsBulkUpdateBody = z.record(z.string(), zJsonValue);

/**
 * Successful Response
 */
export const zUserSettingsBulkUpdateResponse = zUserSettings;

export const zUserSettingDeletePath = z.object({
    key: z.string()
});

export const zUserSettingUpdateBody = zUpdateSettingValue;

export const zUserSettingUpdatePath = z.object({
    key: z.string()
});

/**
 * Successful Response
 */
export const zUserSettingUpdateResponse = zSetting;

export const zAppProviderModelsDiscoverBody = zProviderDiscoveryRequestWritable;

/**
 * Successful Response
 */
export const zAppProviderModelsDiscoverResponse = zProviderDiscoveryResponse;

/**
 * Successful Response
 */
export const zAppSettingsGetResponse = zApplicationSettings;

export const zAppSettingsBulkUpdateBody = zBulkUpdateSettingRequest;

/**
 * Successful Response
 */
export const zAppSettingsBulkUpdateResponse = zApplicationSettings;

export const zAppSettingDeletePath = z.object({
    key: z.string()
});

export const zAppSettingUpdateBody = zUpdateSettingValue;

export const zAppSettingUpdatePath = z.object({
    key: z.string()
});

/**
 * Successful Response
 */
export const zAppSettingUpdateResponse = zSetting;

export const zUserCreateUserBody = zCreateUserRequest;

/**
 * Response Usercreateuser
 *
 * Successful Response
 */
export const zUserCreateUserResponse = z.boolean();

export const zUserDeletePath = z.object({
    user_id: z.string()
});

/**
 * Response Userdelete
 *
 * Successful Response
 */
export const zUserDeleteResponse = z.boolean();

/**
 * Successful Response
 */
export const zToolsGetActiveResponse = zToolInfoList;

/**
 * Successful Response
 */
export const zToolsGetAllResponse = zToolInfoList;

export const zComponentsByTypePath = z.object({
    component_type: zComponentType
});

/**
 * Successful Response
 */
export const zComponentsByTypeResponse = zComponentListResponse;

/**
 * Successful Response
 */
export const zAgentsGetUserAgentsResponse = zUserAgents;

export const zAgentsUpsertAgentProfileBody = zPartialAgentProfile;

/**
 * Successful Response
 */
export const zAgentsUpsertAgentProfileResponse = zAgentProfile;

export const zAgentsDeleteAgentPath = z.object({
    agent_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAgentsDeleteAgentResponse = zAgentProfile;

export const zAgentsGetSubAgentTracesPath = z.object({
    parent_message_id: z.uuid()
});

/**
 * Response Agentsgetsubagenttraces
 *
 * Successful Response
 */
export const zAgentsGetSubAgentTracesResponse = z.array(zSubAgentTrace);
