packages:
  - "apps/*"
  - "packages/*"
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.12'
  - '@better-auth/drizzle-adapter@1.6.12'
  - '@better-auth/kysely-adapter@1.6.12'
  - '@better-auth/memory-adapter@1.6.12'
  - '@better-auth/mongo-adapter@1.6.12'
  - '@better-auth/prisma-adapter@1.6.12'
  - '@better-auth/telemetry@1.6.12'
  - better-auth@1.6.12
  - shadcn@4.8.3
onlyBuiltDependencies:
  - better-sqlite3@12.10.0
  - msw@2.14.6
  - sharp@0.34.5
  - unrs-resolver@1.12.2
