import Providers from "@/app/providers";
import { convertToCssVariables, ThemeColors } from "@/lib/theme";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { cookies } from "next/headers";
import lightTheme from "../../public/themes/light.json";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie =
    cookieStore.get("custom-theme")?.value ?? JSON.stringify(lightTheme);

  let themeStyles = {};

  try {
    const parsedTheme = JSON.parse(decodeURIComponent(themeCookie));
    const rawColors: ThemeColors = parsedTheme.colors;
    themeStyles = convertToCssVariables(rawColors) as React.CSSProperties;
  } catch (e) {
    console.error("Failed to parse theme cookie", e);
  }

  return (
    <html
      style={themeStyles}
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
      suppressHydrationWarning
    >
      <body className="flex h-screen w-screen flex-col overflow-hidden">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
