// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { ApiClient, type Options } from '../sdk.gen';
import type { ChatSessionCreateData, ChatSessionCreateError, ChatSessionCreateResponse, ChatSessionDeleteData, ChatSessionDeleteError, ChatSessionDeleteResponse, ChatSessionGetManyData, ChatSessionGetManyError, ChatSessionGetManyResponse, ChatSessionGetOneData, ChatSessionGetOneError, ChatSessionGetOneResponse, ChatSessionUpdateData, ChatSessionUpdateError, ChatSessionUpdateResponse, FolderCreateData, FolderCreateError, FolderCreateResponse, FolderDeleteData, FolderDeleteError, FolderDeleteResponse, FolderGetManyData, FolderGetManyError, FolderGetManyResponse, FolderGetOneData, FolderGetOneError, FolderGetOneResponse, GetFileData, GetFileError, GetFileResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getFileQueryKey = (options: Options<GetFileData>) => createQueryKey('getFile', options);

/**
 * Get File
 */
export const getFileOptions = (options: Options<GetFileData>) => queryOptions<GetFileResponse, GetFileError, GetFileResponse, ReturnType<typeof getFileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().getFile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getFileQueryKey(options)
});

export const chatSessionGetManyQueryKey = (options?: Options<ChatSessionGetManyData>) => createQueryKey('chatSessionGetMany', options);

/**
 * List Sessions
 */
export const chatSessionGetManyOptions = (options?: Options<ChatSessionGetManyData>) => queryOptions<ChatSessionGetManyResponse, ChatSessionGetManyError, ChatSessionGetManyResponse, ReturnType<typeof chatSessionGetManyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().chatSessionGetMany({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatSessionGetManyQueryKey(options)
});

/**
 * New Session
 */
export const chatSessionCreateMutation = (options?: Partial<Options<ChatSessionCreateData>>): UseMutationOptions<ChatSessionCreateResponse, ChatSessionCreateError, Options<ChatSessionCreateData>> => {
    const mutationOptions: UseMutationOptions<ChatSessionCreateResponse, ChatSessionCreateError, Options<ChatSessionCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().chatSessionCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const chatSessionGetOneQueryKey = (options: Options<ChatSessionGetOneData>) => createQueryKey('chatSessionGetOne', options);

/**
 * Get Session
 */
export const chatSessionGetOneOptions = (options: Options<ChatSessionGetOneData>) => queryOptions<ChatSessionGetOneResponse, ChatSessionGetOneError, ChatSessionGetOneResponse, ReturnType<typeof chatSessionGetOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().chatSessionGetOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatSessionGetOneQueryKey(options)
});

/**
 * Delete Session
 */
export const chatSessionDeleteMutation = (options?: Partial<Options<ChatSessionDeleteData>>): UseMutationOptions<ChatSessionDeleteResponse, ChatSessionDeleteError, Options<ChatSessionDeleteData>> => {
    const mutationOptions: UseMutationOptions<ChatSessionDeleteResponse, ChatSessionDeleteError, Options<ChatSessionDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().chatSessionDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Session
 */
export const chatSessionUpdateMutation = (options?: Partial<Options<ChatSessionUpdateData>>): UseMutationOptions<ChatSessionUpdateResponse, ChatSessionUpdateError, Options<ChatSessionUpdateData>> => {
    const mutationOptions: UseMutationOptions<ChatSessionUpdateResponse, ChatSessionUpdateError, Options<ChatSessionUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().chatSessionUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const folderGetManyQueryKey = (options?: Options<FolderGetManyData>) => createQueryKey('folderGetMany', options);

/**
 * List Folders
 */
export const folderGetManyOptions = (options?: Options<FolderGetManyData>) => queryOptions<FolderGetManyResponse, FolderGetManyError, FolderGetManyResponse, ReturnType<typeof folderGetManyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().folderGetMany({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: folderGetManyQueryKey(options)
});

/**
 * Create Folder
 */
export const folderCreateMutation = (options?: Partial<Options<FolderCreateData>>): UseMutationOptions<FolderCreateResponse, FolderCreateError, Options<FolderCreateData>> => {
    const mutationOptions: UseMutationOptions<FolderCreateResponse, FolderCreateError, Options<FolderCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().folderCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Folder
 */
export const folderDeleteMutation = (options?: Partial<Options<FolderDeleteData>>): UseMutationOptions<FolderDeleteResponse, FolderDeleteError, Options<FolderDeleteData>> => {
    const mutationOptions: UseMutationOptions<FolderDeleteResponse, FolderDeleteError, Options<FolderDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().folderDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const folderGetOneQueryKey = (options: Options<FolderGetOneData>) => createQueryKey('folderGetOne', options);

/**
 * Get Folder
 */
export const folderGetOneOptions = (options: Options<FolderGetOneData>) => queryOptions<FolderGetOneResponse, FolderGetOneError, FolderGetOneResponse, ReturnType<typeof folderGetOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().folderGetOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: folderGetOneQueryKey(options)
});
