// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { ApiClient, type Options } from '../sdk.gen';
import type { AppSettingDeleteData, AppSettingDeleteError, AppSettingsBulkUpdateData, AppSettingsBulkUpdateError, AppSettingsBulkUpdateResponse, AppSettingsGetData, AppSettingsGetError, AppSettingsGetResponse, AppSettingUpdateData, AppSettingUpdateError, AppSettingUpdateResponse, ChatSessionCreateData, ChatSessionCreateError, ChatSessionCreateResponse, ChatSessionDeleteData, ChatSessionDeleteError, ChatSessionDeleteResponse, ChatSessionGetManyData, ChatSessionGetManyError, ChatSessionGetManyResponse, ChatSessionGetOneData, ChatSessionGetOneError, ChatSessionGetOneResponse, ChatSessionUpdateData, ChatSessionUpdateError, ChatSessionUpdateResponse, FolderCreateData, FolderCreateError, FolderCreateResponse, FolderDeleteData, FolderDeleteError, FolderDeleteResponse, FolderGetManyData, FolderGetManyError, FolderGetManyResponse, FolderGetOneData, FolderGetOneError, FolderGetOneResponse, GetFileData, GetFileError, GetFileResponse, UserCreateUserData, UserCreateUserError, UserCreateUserResponse, UserSettingDelete2Data, UserSettingDelete2Error, UserSettingDeleteData, UserSettingDeleteError, UserSettingsBulkUpdateData, UserSettingsBulkUpdateError, UserSettingsBulkUpdateResponse, UserSettingsGetData, UserSettingsGetError, UserSettingsGetResponse, UserSettingUpdateData, UserSettingUpdateError, UserSettingUpdateResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getFileQueryKey = (options: Options<GetFileData>) => createQueryKey('getFile', options);

/**
 * Get File
 */
export const getFileOptions = (options: Options<GetFileData>) => queryOptions<GetFileResponse, GetFileError, GetFileResponse, ReturnType<typeof getFileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().getFile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getFileQueryKey(options)
});

export const chatSessionGetManyQueryKey = (options?: Options<ChatSessionGetManyData>) => createQueryKey('chatSessionGetMany', options);

/**
 * List Sessions
 */
export const chatSessionGetManyOptions = (options?: Options<ChatSessionGetManyData>) => queryOptions<ChatSessionGetManyResponse, ChatSessionGetManyError, ChatSessionGetManyResponse, ReturnType<typeof chatSessionGetManyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().chatSessionGetMany({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatSessionGetManyQueryKey(options)
});

/**
 * New Session
 */
export const chatSessionCreateMutation = (options?: Partial<Options<ChatSessionCreateData>>): UseMutationOptions<ChatSessionCreateResponse, ChatSessionCreateError, Options<ChatSessionCreateData>> => {
    const mutationOptions: UseMutationOptions<ChatSessionCreateResponse, ChatSessionCreateError, Options<ChatSessionCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().chatSessionCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const chatSessionGetOneQueryKey = (options: Options<ChatSessionGetOneData>) => createQueryKey('chatSessionGetOne', options);

/**
 * Get Session
 */
export const chatSessionGetOneOptions = (options: Options<ChatSessionGetOneData>) => queryOptions<ChatSessionGetOneResponse, ChatSessionGetOneError, ChatSessionGetOneResponse, ReturnType<typeof chatSessionGetOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().chatSessionGetOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: chatSessionGetOneQueryKey(options)
});

/**
 * Delete Session
 */
export const chatSessionDeleteMutation = (options?: Partial<Options<ChatSessionDeleteData>>): UseMutationOptions<ChatSessionDeleteResponse, ChatSessionDeleteError, Options<ChatSessionDeleteData>> => {
    const mutationOptions: UseMutationOptions<ChatSessionDeleteResponse, ChatSessionDeleteError, Options<ChatSessionDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().chatSessionDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Session
 */
export const chatSessionUpdateMutation = (options?: Partial<Options<ChatSessionUpdateData>>): UseMutationOptions<ChatSessionUpdateResponse, ChatSessionUpdateError, Options<ChatSessionUpdateData>> => {
    const mutationOptions: UseMutationOptions<ChatSessionUpdateResponse, ChatSessionUpdateError, Options<ChatSessionUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().chatSessionUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const folderGetManyQueryKey = (options?: Options<FolderGetManyData>) => createQueryKey('folderGetMany', options);

/**
 * List Folders
 */
export const folderGetManyOptions = (options?: Options<FolderGetManyData>) => queryOptions<FolderGetManyResponse, FolderGetManyError, FolderGetManyResponse, ReturnType<typeof folderGetManyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().folderGetMany({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: folderGetManyQueryKey(options)
});

/**
 * Create Folder
 */
export const folderCreateMutation = (options?: Partial<Options<FolderCreateData>>): UseMutationOptions<FolderCreateResponse, FolderCreateError, Options<FolderCreateData>> => {
    const mutationOptions: UseMutationOptions<FolderCreateResponse, FolderCreateError, Options<FolderCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().folderCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Folder
 */
export const folderDeleteMutation = (options?: Partial<Options<FolderDeleteData>>): UseMutationOptions<FolderDeleteResponse, FolderDeleteError, Options<FolderDeleteData>> => {
    const mutationOptions: UseMutationOptions<FolderDeleteResponse, FolderDeleteError, Options<FolderDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().folderDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const folderGetOneQueryKey = (options: Options<FolderGetOneData>) => createQueryKey('folderGetOne', options);

/**
 * Get Folder
 */
export const folderGetOneOptions = (options: Options<FolderGetOneData>) => queryOptions<FolderGetOneResponse, FolderGetOneError, FolderGetOneResponse, ReturnType<typeof folderGetOneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().folderGetOne({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: folderGetOneQueryKey(options)
});

export const userSettingsGetQueryKey = (options?: Options<UserSettingsGetData>) => createQueryKey('userSettingsGet', options);

/**
 * Get all user settings
 */
export const userSettingsGetOptions = (options?: Options<UserSettingsGetData>) => queryOptions<UserSettingsGetResponse, UserSettingsGetError, UserSettingsGetResponse, ReturnType<typeof userSettingsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().userSettingsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: userSettingsGetQueryKey(options)
});

/**
 * Bulk update multiple user settings
 */
export const userSettingsBulkUpdateMutation = (options?: Partial<Options<UserSettingsBulkUpdateData>>): UseMutationOptions<UserSettingsBulkUpdateResponse, UserSettingsBulkUpdateError, Options<UserSettingsBulkUpdateData>> => {
    const mutationOptions: UseMutationOptions<UserSettingsBulkUpdateResponse, UserSettingsBulkUpdateError, Options<UserSettingsBulkUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().userSettingsBulkUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a single user setting by key
 */
export const userSettingDeleteMutation = (options?: Partial<Options<UserSettingDeleteData>>): UseMutationOptions<unknown, UserSettingDeleteError, Options<UserSettingDeleteData>> => {
    const mutationOptions: UseMutationOptions<unknown, UserSettingDeleteError, Options<UserSettingDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().userSettingDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update a single user setting by key
 */
export const userSettingUpdateMutation = (options?: Partial<Options<UserSettingUpdateData>>): UseMutationOptions<UserSettingUpdateResponse, UserSettingUpdateError, Options<UserSettingUpdateData>> => {
    const mutationOptions: UseMutationOptions<UserSettingUpdateResponse, UserSettingUpdateError, Options<UserSettingUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().userSettingUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const appSettingsGetQueryKey = (options?: Options<AppSettingsGetData>) => createQueryKey('appSettingsGet', options);

/**
 * Get all application settings
 */
export const appSettingsGetOptions = (options?: Options<AppSettingsGetData>) => queryOptions<AppSettingsGetResponse, AppSettingsGetError, AppSettingsGetResponse, ReturnType<typeof appSettingsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ApiClient.__registry.get().appSettingsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: appSettingsGetQueryKey(options)
});

/**
 * Bulk update multiple application settings
 */
export const appSettingsBulkUpdateMutation = (options?: Partial<Options<AppSettingsBulkUpdateData>>): UseMutationOptions<AppSettingsBulkUpdateResponse, AppSettingsBulkUpdateError, Options<AppSettingsBulkUpdateData>> => {
    const mutationOptions: UseMutationOptions<AppSettingsBulkUpdateResponse, AppSettingsBulkUpdateError, Options<AppSettingsBulkUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().appSettingsBulkUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a single application setting by key
 */
export const appSettingDeleteMutation = (options?: Partial<Options<AppSettingDeleteData>>): UseMutationOptions<unknown, AppSettingDeleteError, Options<AppSettingDeleteData>> => {
    const mutationOptions: UseMutationOptions<unknown, AppSettingDeleteError, Options<AppSettingDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().appSettingDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update a single application setting by key
 */
export const appSettingUpdateMutation = (options?: Partial<Options<AppSettingUpdateData>>): UseMutationOptions<AppSettingUpdateResponse, AppSettingUpdateError, Options<AppSettingUpdateData>> => {
    const mutationOptions: UseMutationOptions<AppSettingUpdateResponse, AppSettingUpdateError, Options<AppSettingUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().appSettingUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create User
 */
export const userCreateUserMutation = (options?: Partial<Options<UserCreateUserData>>): UseMutationOptions<UserCreateUserResponse, UserCreateUserError, Options<UserCreateUserData>> => {
    const mutationOptions: UseMutationOptions<UserCreateUserResponse, UserCreateUserError, Options<UserCreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().userCreateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a single user setting by key
 */
export const userSettingDelete2Mutation = (options?: Partial<Options<UserSettingDelete2Data>>): UseMutationOptions<unknown, UserSettingDelete2Error, Options<UserSettingDelete2Data>> => {
    const mutationOptions: UseMutationOptions<unknown, UserSettingDelete2Error, Options<UserSettingDelete2Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ApiClient.__registry.get().userSettingDelete2({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
