[project]
name = "asterism-workspace"
version = "0.1.0"
description = "Asterism"
authors = [
    { name = "David Bracewell" }
]
readme = "README.md"
requires-python = ">=3.13"


[dependency-groups]
dev = [
    "pytest>=8.0",
    "ruff>=0.14.3",
    "tach>=0.35.0",
]


[tool.uv.workspace]
members = ["packages/*"]

[tool.ruff]
target-version = "py312"
src = ["packages/core/src", "packages/api/src"]

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]

[tool.pyright]
reportPrivateImportUsage = "none"
enableTypeIgnoreComments = true
include = ["packages/*/src"]
stubPath = "packages/*/src"
#typeCheckingMode = "basic"

reportReturnType = "warning"
reportArgumentType = "warning"
reportOperatorIssue = "warning"
reportImportCycles = "warning"
reportDuplicateImport = "warning"
reportUnusedCallResult = "none"
