// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetFileData, GetFileErrors, GetFileResponses, NewChatSessionData, NewChatSessionErrors, NewChatSessionResponses, StreamChatData, StreamChatErrors, StreamChatResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new ApiClient()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ApiClient extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<ApiClient> = new HeyApiRegistry<ApiClient>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        ApiClient.__registry.set(this, args?.key);
    }
    
    /**
     * Get File
     */
    public getFile<ThrowOnError extends boolean = false>(options: Options<GetFileData, ThrowOnError>): RequestResult<GetFileResponses, GetFileErrors, ThrowOnError> {
        return (options.client ?? this.client).get<GetFileResponses, GetFileErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/files/{filename}',
            ...options
        });
    }
    
    /**
     * New Session
     */
    public newChatSession<ThrowOnError extends boolean = false>(options?: Options<NewChatSessionData, ThrowOnError>): RequestResult<NewChatSessionResponses, NewChatSessionErrors, ThrowOnError> {
        return (options?.client ?? this.client).post<NewChatSessionResponses, NewChatSessionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/chat/',
            ...options
        });
    }
    
    /**
     * Async Test
     */
    public streamChat<ThrowOnError extends boolean = false>(options: Options<StreamChatData, ThrowOnError>): RequestResult<StreamChatResponses, StreamChatErrors, ThrowOnError> {
        return (options.client ?? this.client).post<StreamChatResponses, StreamChatErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/api/stream',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
