// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NewSessionResponse
 */
export type NewSessionResponse = {
    /**
     * Id
     */
    id: string;
};

/**
 * StreamRequest
 */
export type StreamRequest = {
    /**
     * Content
     *
     * The prompt content to stream
     */
    content: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetFileData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/files/{filename}';
};

export type GetFileErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
    /**
     * Returns the user's file
     */
    200: Blob | File;
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type NewChatSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/';
};

export type NewChatSessionErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type NewChatSessionError = NewChatSessionErrors[keyof NewChatSessionErrors];

export type NewChatSessionResponses = {
    /**
     * Successful Response
     */
    201: NewSessionResponse;
};

export type NewChatSessionResponse = NewChatSessionResponses[keyof NewChatSessionResponses];

export type StreamChatData = {
    body: StreamRequest;
    path?: never;
    query?: never;
    url: '/api/stream';
};

export type StreamChatErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChatError = StreamChatErrors[keyof StreamChatErrors];

export type StreamChatResponses = {
    /**
     * Stream of NDJSON chunks
     */
    200: unknown;
};
