// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BootstrapAdminRequest
 */
export type BootstrapAdminRequest = {
    /**
     * Setup Token
     */
    setup_token: string;
};

/**
 * BootstrapAdminResponse
 */
export type BootstrapAdminResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Roles
     */
    roles?: Array<string>;
};

/**
 * ChatSessionInfo
 */
export type ChatSessionInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
};

/**
 * ChatSessionList
 */
export type ChatSessionList = Array<ChatSessionInfo>;

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Code
     */
    code: number;
};

/**
 * FolderListResponse
 */
export type FolderListResponse = Array<FolderResponse>;

/**
 * FolderResponse
 */
export type FolderResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Sessions
     */
    sessions?: Array<ChatSessionInfo>;
    /**
     * Parent Folder Id
     */
    parent_folder_id?: string | unknown;
    /**
     * Children
     */
    children?: Array<FolderResponse>;
    [key: string]: unknown;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NewFolderRequest
 */
export type NewFolderRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Parent Folder Id
     */
    parent_folder_id?: string | unknown;
    [key: string]: unknown;
};

/**
 * NewSessionRequest
 */
export type NewSessionRequest = {
    /**
     * Folder Id
     */
    folder_id?: string | unknown;
};

/**
 * NewSessionResponse
 */
export type NewSessionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
};

/**
 * SetupStatusResponse
 */
export type SetupStatusResponse = {
    /**
     * Requires Setup
     */
    requires_setup: boolean;
    /**
     * Is Current User Admin
     */
    is_current_user_admin: boolean;
};

/**
 * StreamRequest
 */
export type StreamRequest = {
    /**
     * Content
     *
     * The prompt content to stream
     */
    content: string;
};

/**
 * UserMeResponse
 */
export type UserMeResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email?: string | unknown;
    /**
     * Display Name
     */
    display_name?: string | unknown;
    /**
     * Roles
     */
    roles?: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetFileData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/files/{filename}';
};

export type GetFileErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not Found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileError = GetFileErrors[keyof GetFileErrors];

export type GetFileResponses = {
    /**
     * Returns the user's file
     */
    200: Blob | File;
};

export type GetFileResponse = GetFileResponses[keyof GetFileResponses];

export type NewChatSessionData = {
    body: NewSessionRequest;
    path?: never;
    query?: never;
    url: '/api/chat/';
};

export type NewChatSessionErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewChatSessionError = NewChatSessionErrors[keyof NewChatSessionErrors];

export type NewChatSessionResponses = {
    /**
     * Successful Response
     */
    201: NewSessionResponse;
};

export type NewChatSessionResponse = NewChatSessionResponses[keyof NewChatSessionResponses];

export type ListChatSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/list';
};

export type ListChatSessionsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type ListChatSessionsError = ListChatSessionsErrors[keyof ListChatSessionsErrors];

export type ListChatSessionsResponses = {
    /**
     * Successful Response
     */
    200: ChatSessionList;
};

export type ListChatSessionsResponse = ListChatSessionsResponses[keyof ListChatSessionsResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserMeResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetSetupStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/setup/status';
};

export type GetSetupStatusErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type GetSetupStatusError = GetSetupStatusErrors[keyof GetSetupStatusErrors];

export type GetSetupStatusResponses = {
    /**
     * Successful Response
     */
    200: SetupStatusResponse;
};

export type GetSetupStatusResponse = GetSetupStatusResponses[keyof GetSetupStatusResponses];

export type BootstrapAdminData = {
    body: BootstrapAdminRequest;
    path?: never;
    query?: never;
    url: '/api/setup/bootstrap-admin';
};

export type BootstrapAdminErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Conflict
     */
    409: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Service Unavailable
     */
    503: ErrorDetail;
};

export type BootstrapAdminError = BootstrapAdminErrors[keyof BootstrapAdminErrors];

export type BootstrapAdminResponses = {
    /**
     * Successful Response
     */
    200: BootstrapAdminResponse;
};

export type BootstrapAdminResponse2 = BootstrapAdminResponses[keyof BootstrapAdminResponses];

export type AdminPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/ping';
};

export type AdminPingErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Forbidden
     */
    403: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type AdminPingError = AdminPingErrors[keyof AdminPingErrors];

export type AdminPingResponses = {
    /**
     * Successful Response
     */
    200: {
        status?: string;
    };
};

export type AdminPingResponse = AdminPingResponses[keyof AdminPingResponses];

export type DeleteFolderData = {
    body?: never;
    path: {
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/folders/{folder_id}';
};

export type DeleteFolderErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorDetail;
};

export type DeleteFolderError = DeleteFolderErrors[keyof DeleteFolderErrors];

export type DeleteFolderResponses = {
    /**
     * Response 200 Deletefolder
     *
     * OK
     */
    200: string;
    /**
     * Successful Response
     */
    201: unknown;
};

export type DeleteFolderResponse = DeleteFolderResponses[keyof DeleteFolderResponses];

export type CreateFolderData = {
    body: NewFolderRequest;
    path?: never;
    query?: never;
    url: '/api/folders/';
};

export type CreateFolderErrors = {
    /**
     * Bad Request
     */
    400: ErrorDetail;
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFolderError = CreateFolderErrors[keyof CreateFolderErrors];

export type CreateFolderResponses = {
    /**
     * OK
     */
    200: FolderResponse;
    /**
     * Successful Response
     */
    201: FolderResponse;
};

export type CreateFolderResponse = CreateFolderResponses[keyof CreateFolderResponses];

export type ListFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/folders/list';
};

export type ListFoldersErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Not found
     */
    404: ErrorDetail;
};

export type ListFoldersError = ListFoldersErrors[keyof ListFoldersErrors];

export type ListFoldersResponses = {
    /**
     * Successful Response
     */
    200: FolderListResponse;
};

export type ListFoldersResponse = ListFoldersResponses[keyof ListFoldersResponses];

export type StreamChatData = {
    body: StreamRequest;
    path?: never;
    query?: never;
    url: '/api/stream';
};

export type StreamChatErrors = {
    /**
     * Unauthorized
     */
    401: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChatError = StreamChatErrors[keyof StreamChatErrors];

export type StreamChatResponses = {
    /**
     * Stream of NDJSON chunks
     */
    200: unknown;
};
