#!/bin/bash

AUTH_DB_PATH="${BETTER_AUTH_DB_PATH:-"${STORAGE_ROOT:-/storage}/users.db"}"
[ -f "$1" ] && source "$1"

if [ -f "$AUTH_DB_PATH" ]; then
  echo "Removing auth database at $AUTH_DB_PATH"
  rm "$AUTH_DB_PATH"
fi

npx auth@latest migrate --yes